-- Migration 0006: Vietnamese Recipe Bank (Curated Dishes across 10 Categories)
-- Generated from @frigo/recipes canonical recipe catalog with distinct authentic dish photos

-- 1. Ensure Canonical Ingredients exist
INSERT OR IGNORE INTO ingredients (id, name_vi, name_en, category, default_unit, default_shelf_life_days, icon) VALUES
('PORK_RIBS', 'Sườn heo / Sườn non', 'Pork ribs', 'meat', 'g', 3, '🍖'),
('CRAB_MEAT', 'Cua đồng / Cua thịt', 'Crab meat / Field crab', 'seafood', 'g', 2, '🦀'),
('SQUID', 'Mực tươi', 'Squid', 'seafood', 'g', 2, '🦑'),
('FISH_FRESHWATER', 'Cá tươi (Cá lóc, điêu hồng, rô)', 'Freshwater fish', 'seafood', 'g', 2, '🐟'),
('BITTER_MELON', 'Khổ qua / Mướp đắng', 'Bitter melon', 'vegetable', 'piece', 5, '🥒'),
('WINTER_MELON', 'Bí đao', 'Winter melon', 'vegetable', 'piece', 10, '🍈'),
('PUMPKIN', 'Bí đỏ', 'Pumpkin', 'vegetable', 'piece', 20, '🎃'),
('PINEAPPLE', 'Dứa / Thơm', 'Pineapple', 'fruit', 'piece', 7, '🍍'),
('BEAN_SPROUTS', 'Giá đỗ', 'Bean sprouts', 'vegetable', 'g', 3, '🌱'),
('CHAYOTE', 'Su su', 'Chayote', 'vegetable', 'piece', 10, '🍐'),
('LEMONGRASS', 'Sả tươi', 'Lemongrass', 'spice', 'piece', 14, '🌾'),
('LIME', 'Chanh tươi', 'Lime', 'fruit', 'piece', 14, '🍋'),
('RICE_PAPER', 'Bánh tráng cuốn', 'Rice paper', 'grain', 'pack', 180, '🫓'),
('MUSHROOM', 'Nấm tươi / nấm hương', 'Mushroom', 'vegetable', 'g', 5, '🍄');

-- 2. Seed Vietnamese Recipes with Unique Authentic Photography
INSERT INTO recipes (id, slug, title, description, cuisine, cook_time_minutes, servings, difficulty, image_url, tags) VALUES
('vn-canh-01', 'canh-chua-ca-loc-nam-bo', 'Canh chua cá lóc Nam Bộ', 'Bát canh chua cá lóc đậm đà vị chua thanh của me, ngọt mát từ dứa, cà chua, đậu bắp và giá đỗ chuẩn vị miền Tây.', 'vietnamese', 25, 4, 'medium', 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80', '["Món canh","Nam Bộ","Thanh nhiệt","Cá tươi","cat:mon_canh","region:nam"]'),
('vn-canh-02', 'canh-cua-dong-rau-day-mong-toi', 'Canh cua đồng mồng tơi mướp hương', 'Món canh giải nhiệt trứ danh mùa hè miền Bắc với tảng riêu cua đồng béo ngậy nấu cùng mồng tơi và mướp hương thanh mát.', 'vietnamese', 20, 4, 'medium', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', '["Món canh","Miền Bắc","Mùa hè","Cua đồng","cat:mon_canh","region:bac"]'),
('vn-canh-03', 'canh-kho-qua-nhoi-thit', 'Canh khổ qua nhồi thịt thanh mát', 'Trái khổ qua dồn thịt heo xay ngọt đậm vị, nước dùng ngọt thanh giúp thanh nhiệt giải độc cơ thể.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80', '["Món canh","Thanh nhiệt","Truyền thống","Dễ ăn","cat:mon_canh","region:nam"]'),
('vn-canh-04', 'canh-suon-bi-dao', 'Canh sườn hầm bí đao ngọt thanh', 'Sườn heo ninh mềm róc xương kết hợp vị ngọt thanh của bí đao xanh tạo nên món canh dễ ăn cho cả gia đình.', 'vietnamese', 35, 4, 'easy', 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80', '["Món canh","Bổ dưỡng","Cơm nhà","Trẻ em thích","cat:mon_canh","region:toan_quoc"]'),
('vn-canh-05', 'canh-bi-do-thit-bam', 'Canh bí đỏ thịt bằm hạt sen', 'Bí đỏ bùi bùi sánh mịn cùng thịt băm ngọt đậm đà, bổ sung nhiều vitamin A và dưỡng chất quý giá.', 'vietnamese', 20, 4, 'easy', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80', '["Món canh","Bổ não","Nhanh gọn","Dưới 20 phút","cat:mon_canh","region:toan_quoc"]'),
('vn-canh-06', 'canh-ngao-nau-chua-thi-la', 'Canh ngao nấu chua thì là', 'Vị ngọt thanh khiết của ngao hòa cùng vị chua dịu của dứa, cà chua và hương thơm đặc trưng của rau thì là.', 'vietnamese', 20, 4, 'easy', 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80', '["Món canh","Hải sản","Thanh mát","Hà Nội","cat:mon_canh","region:bac"]'),
('vn-kho-01', 'thit-kho-trung', 'Thịt kho tàu nước dừa trứng béo ngậy', 'Thịt ba chỉ vuông vức óng ả màu cánh gián, ninh nhừ mềm tan trong nước dừa xiêm cùng trứng gà bùi bùi chuẩn Tết miền Nam.', 'vietnamese', 45, 4, 'medium', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', '["Món kho","Món mặn","Nam Bộ","Ăn cơm nhiều","cat:mon_kho","region:nam"]'),
('vn-kho-02', 'ca-loc-kho-to-tieu-den', 'Cá lóc kho tộ tiêu đen cay nồng', 'Thịt cá lóc đồng săn chắc ngấm đậm vị mắm đường, thơm nức tiêu đen xay và tóp mỡ giòn rụm trong niêu đất.', 'vietnamese', 30, 3, 'medium', 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80', '["Món kho","Đặc sản","Đậm đà","Niêu đất","cat:mon_kho","region:nam"]'),
('vn-kho-03', 'ga-ta-kho-gung-sa', 'Gà ta kho gừng sả đậm đà', 'Thịt gà ta da giòn thịt dai ngọt quyện trong lớp sốt kho vàng óng, thơm ấm nồng gừng tươi thái sợi và sả giã dập.', 'vietnamese', 25, 4, 'easy', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', '["Món kho","Món mặn","Ấm bụng","Mùa đông","cat:mon_kho","region:toan_quoc"]'),
('vn-kho-04', 'suon-heo-xao-chua-ngot', 'Sườn heo xào chua ngọt chuẩn vị', 'Từng dẻ sườn non áo lớp sốt đỏ au chua thanh ngọt dịu từ giấm táo và cà chua, thịt mềm róc xương đậm vị cơm nhà.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80', '["Món mặn","Trẻ em thích","Chua ngọt","Đậm đà","cat:mon_kho","region:bac"]'),
('vn-kho-05', 'tom-rim-man-ngot', 'Tôm rim mặn ngọt mắm đường tỏi ớt', 'Tôm đồng hoặc tôm thẻ tươi vỏ giòn giòn, thịt dai ngọt rim kẹo mặn mặn ngọt ngọt, ăn với cơm nóng cực kỳ đưa miệng.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=800&q=80', '["Món rim","Hải sản","Dưới 20 phút","Đưa cơm","cat:mon_kho","region:toan_quoc"]'),
('vn-kho-06', 'thit-ba-chi-kho-cu-cai', 'Thịt ba chỉ kho củ cải trắng', 'Thịt ba chỉ ngậy béo kho cùng từng khúc củ cải trắng hút trọn vị ngọt mặn tinh túy, mềm tan trong miệng.', 'vietnamese', 35, 4, 'easy', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '["Món kho","Món mặn","Cơm nhà","Mùa đông","cat:mon_kho","region:bac"]'),
('vn-xao-01', 'rau-muong-xao-toi', 'Rau muống xào tỏi xanh giòn', 'Rau muống ngọn non xanh mướt giòn sần sật dậy mùi thơm lừng của tỏi ta phi vàng xém cạnh, linh hồn bữa cơm gia đình.', 'vietnamese', 10, 3, 'easy', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80', '["Món xào","Rau củ","Dưới 20 phút","Nhanh gọn","cat:mon_xao","region:toan_quoc"]'),
('vn-xao-02', 'bo-xao-can-toi-hanh-tay', 'Bò xào cần tỏi hành tây mềm ngọt', 'Thịt bò thăn thái mỏng xào lửa lớn giữ trọn độ mềm mọng nước, kết hợp mùi thơm nồng đặc trưng của cần tây và tỏi tây.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80', '["Món xào","Thịt bò","Dưới 20 phút","Bổ dưỡng","cat:mon_xao","region:bac"]'),
('vn-xao-03', 'muc-xao-can-toi-dua', 'Mực ống xào cần tỏi dứa chua ngọt', 'Mực ống tươi dày mình giòn sần sật xào cùng dứa thơm chua dịu, cần tây và ớt chuông đậm đà thanh vị biển.', 'vietnamese', 15, 3, 'medium', 'https://images.unsplash.com/photo-1535400255456-984241443b29?auto=format&fit=crop&w=800&q=80', '["Món xào","Hải sản","Dưới 20 phút","Đãi khách","cat:mon_xao","region:toan_quoc"]'),
('vn-xao-04', 'thit-bo-xao-bong-cai', 'Thịt bò xào bông cải xanh cà rốt', 'Súp lơ xanh giòn mát xào cùng thịt bò mềm và cà rốt tỉa hoa, món xào đầy đặn sắc màu và giàu chất xơ.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80', '["Món xào","Bổ dưỡng","Healthy","Cơm nhà","cat:mon_xao","region:toan_quoc"]'),
('vn-xao-05', 'su-su-xao-trung-ga', 'Su su xào trứng gà thanh ngọt', 'Su su bào sợi giòn ngọt tự nhiên ôm lấy từng mảng trứng gà vàng ươm béo ngậy, món ăn thanh đạm dễ làm.', 'vietnamese', 12, 3, 'easy', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80', '["Món xào","Tiết kiệm","Dưới 20 phút","Thanh đạm","cat:mon_xao","region:bac"]'),
('vn-xao-06', 'dau-cove-xao-thit-bo', 'Đậu cô ve xào thịt bò giòn ngọt', 'Đậu cô ve tước xơ bẻ khúc xào vừa chín tới giữ trọn màu xanh non mướt, kết hợp thịt bò mềm thơm ngất ngây.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80', '["Món xào","Bò xào","Dưới 20 phút","Cơm nhà","cat:mon_xao","region:toan_quoc"]'),
('vn-chien-01', 'dau-phu-sot-ca-chua', 'Đậu phụ lướt ván sốt cà chua', 'Miếng đậu phụ vàng mềm núng nính phủ lớp sốt cà chua đỏ au sánh mịn quyện cùng hành hoa thơm nức mũi.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', '["Món chiên","Tiết kiệm","Dưới 20 phút","Quốc dân","cat:mon_chien","region:toan_quoc"]'),
('vn-chien-02', 'trung-chien-thit-bam-nam-rom', 'Trứng chiên thịt bằm nấm rơm', 'Món trứng chiên phồng xốp vàng rực, bên trong đầy đặn thịt heo băm đậm đà và nấm ngọt giòn sần sật.', 'vietnamese', 12, 3, 'easy', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80', '["Món chiên","Nhanh gọn","Dưới 20 phút","Được yêu thích","cat:mon_chien","region:toan_quoc"]'),
('vn-chien-03', 'canh-ga-chien-nuoc-mam', 'Cánh gà chiên nước mắm tỏi ớt', 'Cánh gà chiên vàng giòn rụm bên ngoài mọng nước bên trong, lắc đều cùng sốt mắm tỏi ớt ngọt mặn dính tay hấp dẫn.', 'vietnamese', 25, 4, 'medium', 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80', '["Món chiên","Ăn vặt","Món nhậu","Trẻ em mê","cat:mon_chien","region:toan_quoc"]'),
('vn-chien-04', 'cha-ca-hai-phong', 'Chả cá chiên thì là hạt tiêu', 'Chả cá thác lác hoặc cá điêu hồng quết dẻo quánh, trộn nhiều thì là và hạt tiêu đập dập rán vàng phồng thơm phức.', 'vietnamese', 20, 4, 'medium', 'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?auto=format&fit=crop&w=800&q=80', '["Món chiên","Hải sản","Đặc sản","Bắc Bộ","cat:mon_chien","region:bac"]'),
('vn-chien-05', 'nem-ran-truyen-thong-ha-noi', 'Nem rán truyền thống Hà Nội giòn rụm', 'Vỏ nem vàng rộm giòn tan rụm, nhân thịt băm mộc nhĩ nấm hương miến dong và trứng gà thơm phức chấm mắm chua ngọt.', 'vietnamese', 35, 4, 'hard', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', '["Món chiên","Nem rán","Tiệc tùng","Truyền thống","cat:mon_chien","region:bac"]'),
('vn-chien-06', 'ca-ro-phi-chien-gion-mam-gung', 'Cá rô phi chiên giòn chấm mắm gừng', 'Cá rô phi làm sạch khía vảy chiên giòn tan từ vây đến da, thịt cá trắng ngọt chấm nước mắm gừng ớt ấm nồng.', 'vietnamese', 25, 4, 'easy', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80', '["Món chiên","Cá tươi","Cơm nhà","Dễ làm","cat:mon_chien","region:toan_quoc"]'),
('vn-hap-01', 'ga-ta-hap-la-chanh', 'Gà ta hấp lá chanh da giòn thịt ngọt', 'Gà thả vườn hấp cách thủy giữ nguyên 100% vị ngọt thanh tinh khiết, da gà vàng óng giòn sần sật thơm nức lá chanh thái chỉ.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '["Món hấp","Gà ta","Thanh đạm","Đãi tiệc","cat:mon_hap_luoc","region:bac"]'),
('vn-hap-02', 'thit-ba-chi-luoc-mam-tom', 'Thịt ba chỉ luộc chấm mắm tôm cà pháo', 'Thịt ba chỉ luộc trắng ngần, nạc mỡ đan xen đều tăm tắp thái mỏng tang, chấm mắm tôm đánh sủi bọt bông và cà pháo muối giòn.', 'vietnamese', 20, 4, 'easy', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80', '["Món luộc","Món thanh","Dưới 20 phút","Kinh điển","cat:mon_hap_luoc","region:bac"]'),
('vn-hap-03', 'ca-dieu-hong-hap-hanh-gung', 'Cá điêu hồng hấp hành gừng xì dầu', 'Cá điêu hồng tươi hấp nguyên con giữ trọn vị ngọt tự nhiên, quyện trong sốt xì dầu thơm nồng gừng sợi và hành hoa chần dầu sôi.', 'vietnamese', 25, 4, 'medium', 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', '["Món hấp","Cá tươi","Tươi ngọt","Đãi khách","cat:mon_hap_luoc","region:toan_quoc"]'),
('vn-hap-04', 'rau-cu-luoc-kho-quet', 'Rau củ luộc thập cẩm kho quẹt tóp mỡ', 'Mẹt rau củ vườn nhà tươi non giòn ngọt chấm ngập trong niêu kho quẹt tóp mỡ tôm khô thơm nức mũi chuẩn vị Nam Bộ.', 'vietnamese', 20, 4, 'easy', 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=800&q=80', '["Món luộc","Rau củ","Kho quẹt","Món Nam","cat:mon_hap_luoc","region:nam"]'),
('vn-hap-05', 'muc-hap-gung-sa', 'Mực ống hấp gừng sả giòn ngọt', 'Mực ống tươi dày mình hấp cùng sả cây đập dập và gừng non, từng miếng mực giòn ngọt sần sật mọng nước.', 'vietnamese', 12, 3, 'easy', 'https://images.unsplash.com/photo-1535400255456-984241443b29?auto=format&fit=crop&w=800&q=80', '["Món hấp","Hải sản","Dưới 20 phút","Tươi ngọt","cat:mon_hap_luoc","region:trung"]'),
('vn-hap-06', 'tom-hap-nuoc-dua-tuoi', 'Tôm hấp nước dừa tươi ngọt lịm', 'Tôm sú tươi roi rói hấp cùng nước dừa xiêm ngọt lịm, vỏ tôm đỏ au thịt tôm săn chắc ngọt ngào hương dừa thanh tao.', 'vietnamese', 12, 3, 'easy', 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=800&q=80', '["Món hấp","Hải sản","Dưới 20 phút","Đặc sản Nam Bộ","cat:mon_hap_luoc","region:nam"]'),
('vn-cuon-01', 'goi-cuon-tom-thit-nam-bo', 'Gỏi cuốn tôm thịt chấm tương phộng', 'Cuốn bánh tráng trong veo lộ rõ tôm đỏ au, thịt ba chỉ, bún tươi và rau húng quế mát lành, chấm tương đen đậu phộng béo bùi.', 'vietnamese', 20, 4, 'medium', 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', '["Món cuốn","Healthy","Mùa hè","Đặc sản Nam Bộ","cat:mon_cuon_nom","region:nam"]'),
('vn-cuon-02', 'pho-cuon-bo-ha-noi', 'Phở cuốn bò xào rau thơm Hà Nội', 'Bánh phở vuông mềm mượt cuốn gọn thịt bò xào tỏi thơm nức mũi và rau xà lách kinh giới, chấm nước mắm chua ngọt thanh tao.', 'vietnamese', 20, 3, 'easy', 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80', '["Món cuốn","Hà Nội","Phố Trúc Bạch","Dưới 20 phút","cat:mon_cuon_nom","region:bac"]'),
('vn-cuon-03', 'nom-hoa-chuoi-tai-heo', 'Nộm hoa chuối tai heo giòn sần sật', 'Hoa chuối bào mỏng ngâm trắng tinh quyện cùng tai heo luộc giòn sần sật, vị chua ngọt thanh tao cùng lạc rang bùi bùi.', 'vietnamese', 25, 4, 'medium', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80', '["Món nộm","Khai vị","Giòn sần sật","Ăn không ngấy","cat:mon_cuon_nom","region:bac"]'),
('vn-cuon-04', 'goi-ga-xe-phay-bap-cai', 'Gỏi gà xé phay bắp cải hành tây', 'Thịt gà ta luộc xé sợi dai ngọt trộn cùng bắp cải bào mỏng giòn rụm, hành tây chua ngọt dịu và rau răm thơm the the.', 'vietnamese', 20, 4, 'easy', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', '["Món gỏi","Miền Trung","Healthy","Đặc sản","cat:mon_cuon_nom","region:trung"]'),
('vn-cuon-05', 'nom-du-du-bo-kho', 'Nộm đu đủ bò khô phố cổ Hà Nội', 'Sợi đu đủ xanh nạo giòn sần sật hòa quyện nước mắm giấm chua ngọt cay cay, điểm xuyết từng sợi bò khô nâu óng thơm phức.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', '["Món nộm","Phố Cổ","Ăn vặt","Dưới 20 phút","cat:mon_cuon_nom","region:bac"]'),
('vn-cuon-06', 'nem-lui-hue-nuong-sa', 'Nem lụi nướng sả cuốn bánh tráng', 'Thịt heo xay quết mịn bọc quanh thân cây sả tươi nướng xém cạnh thơm lừng, cuốn bánh tráng rau sống chấm nước lèo bùi ngậy.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80', '["Món nướng","Xứ Huế","Món cuốn","Đặc sản","cat:mon_cuon_nom","region:trung"]'),
('vn-bun-01', 'pho-bo-tai-lan-ha-noi', 'Phở bò tái lăn Hà Nội nước dùng trong vắt', 'Thịt bò thăn đảo tái lăn trên chảo lửa ngùn ngụt cùng tỏi gừng, chan nước dùng ninh xương ống thơm hồi quế thảo quả.', 'vietnamese', 35, 4, 'hard', 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80', '["Phở","Hà Nội","Tinh hoa ẩm thực","Bữa sáng / tối","cat:mon_bun_pho","region:bac"]'),
('vn-bun-02', 'bun-cha-ha-noi-than-hoa', 'Bún chả nướng than hoa Hà Nội', 'Chả miếng ba chỉ nướng xém vàng ươm và chả băm viên đậm vị, thả trong bát nước mắm ấm chua ngọt dưa góp đu đủ.', 'vietnamese', 35, 4, 'medium', 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80', '["Bún chả","Hà Nội","Đặc sản","Ăn trưa","cat:mon_bun_pho","region:bac"]'),
('vn-bun-03', 'bun-bo-hue-chuan-vi', 'Bún bò xứ Huế giò heo chả cua sả ớt', 'Tô bún bò cay nồng thơm lừng mùi sả phi mắm ruốc, nước dùng ngọt đậm đà từ xương ống cùng bắp bò giòn sần sật.', 'vietnamese', 40, 4, 'hard', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80', '["Bún bò","Xứ Huế","Cay nồng","Đậm vị","cat:mon_bun_pho","region:trung"]'),
('vn-bun-04', 'bun-rieu-cua-dong', 'Bún riêu cua đồng bắp bò giấm bỗng', 'Bát bún riêu đỏ cam óng ả với tảng riêu cua đồng béo ngậy, đậu phụ rán giòn, thịt bò tái chần và nước dùng chua dịu giấm bỗng.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80', '["Bún riêu","Hà Nội","Mùa hè","Cua đồng","cat:mon_bun_pho","region:bac"]'),
('vn-bun-05', 'bun-thit-nuong-nam-bo', 'Bún thịt nướng Nam Bộ chả giò mỡ hành', 'Thịt nướng vỉ thơm lừng mè rang và sả ớt, ăn kèm bún tươi, mỡ hành xanh mướt, đậu phộng rang giòn và nước mắm chua ngọt.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80', '["Bún thịt nướng","Nam Bộ","Ăn trưa","Đưa miệng","cat:mon_bun_pho","region:nam"]'),
('vn-bun-06', 'mien-ga-nam-huong', 'Miến gà nấm hương mộc nhĩ thanh tao', 'Sợi miến dong dai trong vắt nấu trong nước luộc gà ngọt thanh tao, thơm ngát nấm hương rừng và thịt gà xé phay mềm ngọt.', 'vietnamese', 25, 4, 'easy', 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80', '["Miến gà","Hà Nội","Thanh đạm","Ấm bụng","cat:mon_bun_pho","region:bac"]'),
('vn-chay-01', 'dau-phu-kho-nam-dong-co', 'Đậu phụ kho nấm đông cô tiêu đen', 'Đậu phụ rán vàng óng kho ngấm đượm sốt tương đen cùng nấm đông cô ngọt bùi, thơm nức tiêu sọ xay cay the ấm nồng.', 'vietnamese', 20, 3, 'easy', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', '["Món chay","Thanh lọc","Đậu phụ","Dưới 20 phút","cat:mon_chay","region:toan_quoc"]'),
('vn-chay-02', 'canh-nam-hat-sen-tao-do', 'Canh nấm hạt sen táo đỏ thanh lọc', 'Nước canh trong veo ngọt ngào từ củ quả ninh tự nhiên, hạt sen bở tơi bùi béo cùng các loại nấm tươi bổ dưỡng an thần.', 'vietnamese', 25, 4, 'easy', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', '["Món chay","Bổ dưỡng","An thần","Thanh nhiệt","cat:mon_chay","region:toan_quoc"]'),
('vn-chay-03', 'mi-xao-chay-rau-nam', 'Mì xào giòn chay nấm rau củ', 'Sợi mì xào vàng thơm tơi sợi không bết dính, đảo cùng nấm đùi gà dai giòn, cải ngọt và cà rốt ngập tràn sốt dầu hào chay.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80', '["Món chay","Mì xào","Dưới 20 phút","Nhanh gọn","cat:mon_chay","region:toan_quoc"]'),
('vn-chay-04', 'ca-tim-nuong-mo-hanh', 'Cà tím nướng mỡ hành nước tương tỏi ớt', 'Cà tím nướng than thơm lừng mùi khói, thịt cà mềm mọng ngọt ngào phủ ngập mỡ hành béo ngậy và nước tương tỏi ớt.', 'vietnamese', 20, 3, 'easy', 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=800&q=80', '["Món chay","Dân dã","Nam Bộ","Ngon miệng","cat:mon_chay","region:nam"]'),
('vn-chay-05', 'dau-hu-non-sot-nam-rom', 'Đậu hũ non sốt nấm rơm dầu hào', 'Từng lát đậu hũ non mềm mịn như lụa tan ngay đầu lưỡi, ngập trong lớp sốt nấm rơm bóng bẩy đậm đà sánh ngậy.', 'vietnamese', 15, 3, 'easy', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', '["Món chay","Đậu hũ non","Dưới 20 phút","Mềm mịn","cat:mon_chay","region:toan_quoc"]'),
('vn-chay-06', 'canh-cai-nau-dau-phu-non', 'Canh cải xanh gừng đậu phụ thanh mát', 'Bát canh cải bẹ xanh tươi non nấu cùng gừng tươi đập dập cay nồng và đậu phụ béo mềm, xua tan hàn khí ấm bụng.', 'vietnamese', 12, 4, 'easy', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80', '["Món canh","Món chay","Ấm bụng","Dưới 20 phút","cat:mon_chay","region:toan_quoc"]'),
('vn-sang-01', 'com-chien-trung-toi-hanh-hoa', 'Cơm chiên trứng vàng giòn tỏi phi', 'Hạt cơm nguội vàng óng bọc đều lớp trứng gà bóng bẩy, chiên giòn tơi xốp dậy mùi thơm nức của tỏi phi và hành hoa.', 'vietnamese', 12, 2, 'easy', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80', '["Ăn sáng","Cơm chiên","Dưới 20 phút","Tiết kiệm","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-sang-02', 'banh-mi-op-la-pate', 'Bánh mì ốp la pate dưa leo', 'Ổ bánh mì giòn tan kẹp quả trứng ốp la lòng đào béo ngậy, quét đẫm lớp pate Hải Phòng thơm lừng và dưa leo mát rượi.', 'vietnamese', 10, 2, 'easy', 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?auto=format&fit=crop&w=800&q=80', '["Bánh mì","Ăn sáng","Dưới 20 phút","Quốc dân","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-sang-03', 'chao-thit-bam-gung-tia-to', 'Cháo thịt bằm gừng tía tô giải cảm', 'Bát cháo hoa sánh mịn nấu từ hạt gạo rang thơm, thịt nạc heo băm ngọt lịm cùng lá tía tô và gừng già giải cảm hiệu quả.', 'vietnamese', 20, 3, 'easy', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', '["Cháo","Giải cảm","Ăn sáng","Ấm bụng","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-sang-04', 'mi-tom-xao-bo-trung-long-dao', 'Mì gói xào bò trứng lòng đào', 'Sợi mì tôm chần xào giòn dai không nát, hòa cùng thịt bò xào mềm ngọt, rau cải giòn mát và quả trứng ốp lòng đào béo ngậy.', 'vietnamese', 15, 2, 'easy', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80', '["Mì xào","Ăn nhanh","Dưới 20 phút","Sinh viên","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-sang-05', 'trung-cuon-rau-cu-han-quoc', 'Trứng cuộn rau củ mềm mịn', 'Trứng gà đánh mịn cuộn tròn nhiều lớp xen kẽ cà rốt và hành hoa thái hạt lựu xinh xắn, món ăn sáng giàu protein cho cả nhà.', 'vietnamese', 12, 2, 'easy', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80', '["Trứng cuộn","Ăn sáng","Dưới 20 phút","Bé thích","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-sang-06', 'sup-ga-ngo-non-nam-huong', 'Súp gà ngô non nấm hương trứng hoa', 'Bát súp nóng hổi sánh óng ánh với những vân trứng hoa bay lượn, thịt gà xé ngọt mềm cùng hạt ngô ngọt giòn bùi.', 'vietnamese', 18, 4, 'easy', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80', '["Súp","Ăn sáng","Dưới 20 phút","Khai vị","cat:mon_nhanh_sang","region:toan_quoc"]'),
('vn-lau-01', 'lau-rieu-cua-dong-bap-bo-suon-sun', 'Lẩu riêu cua đồng sườn sụn bắp bò', 'Nồi lẩu riêu cua bốc khói nghi ngút thơm nồng giấm bỗng, tảng riêu cua vàng ngậy nhúng bắp bò hoa giòn và sườn non sần sật.', 'vietnamese', 45, 6, 'hard', 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80', '["Món lẩu","Tiệc gia đình","Hà Nội","Cực phẩm","cat:mon_lau_tiec","region:bac"]'),
('vn-lau-02', 'lau-ga-la-giang-chua-cay', 'Lẩu gà ta lá giang chua cay Nam Bộ', 'Thịt gà ta da giòn thịt săn chắc nấu cùng lá giang vò dập chua thanh thanh the mát, làm ấm lòng những ngày mưa.', 'vietnamese', 40, 5, 'medium', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80', '["Món lẩu","Nam Bộ","Gà ta","Chua cay","cat:mon_lau_tiec","region:nam"]'),
('vn-lau-03', 'lau-hai-san-thap-cam-chua-cay', 'Lẩu hải sản tôm mực chua cay', 'Nồi lẩu hải sản ngập tràn tôm sú tươi roi rói, mực ống giòn sần sật, nước dùng Tom Yum chua cay ngọt đậm vị biển.', 'vietnamese', 35, 5, 'medium', 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80', '["Món lẩu","Hải sản","Chua cay","Tiệc tùng","cat:mon_lau_tiec","region:toan_quoc"]'),
('vn-lau-04', 'lau-nam-thap-cam-thanh-dam', 'Lẩu nấm thập cẩm gà ta thanh đạm bổ dưỡng', 'Nước lẩu hầm từ gà ta và các vị thảo mộc thiên nhiên ngọt lịm, nhúng cùng 6 loại nấm tươi giòn dai thanh lọc cơ thể.', 'vietnamese', 40, 5, 'medium', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', '["Món lẩu","Nấm tươi","Bổ dưỡng","Healthy","cat:mon_lau_tiec","region:toan_quoc"]'),
('vn-lau-05', 'lau-ca-thac-lac-kho-qua', 'Lẩu cá thác lác khổ qua thanh mát', 'Chả cá thác lác quết dai dẻo vo viên thả vào nồi nước dùng thanh ngọt, nhúng cùng khổ qua bào mỏng giòn không đắng.', 'vietnamese', 30, 4, 'medium', 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80', '["Món lẩu","Đặc sản miền Tây","Khổ qua","Thanh mát","cat:mon_lau_tiec","region:nam"]')
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  cuisine = excluded.cuisine,
  cook_time_minutes = excluded.cook_time_minutes,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  image_url = excluded.image_url,
  tags = excluded.tags;

-- 3. Seed Recipe Ingredients
INSERT INTO recipe_ingredients (id, recipe_id, ingredient_id, name, required_quantity, unit, is_optional) VALUES
('vn-canh-01_ing_1', 'vn-canh-01', 'FISH_FRESHWATER', 'Cá lóc tươi (cắt khúc)', 400, 'g', 0),
('vn-canh-01_ing_2', 'vn-canh-01', 'TOMATO', 'Cà chua', 2, 'piece', 0),
('vn-canh-01_ing_3', 'vn-canh-01', 'PINEAPPLE', 'Dứa / Thơm (thái lát)', 1, 'piece', 0),
('vn-canh-01_ing_4', 'vn-canh-01', 'BEAN_SPROUTS', 'Giá đỗ sống', 150, 'g', 0),
('vn-canh-01_ing_5', 'vn-canh-01', 'SCALLION', 'Ngò gai & ngò ôm', 1, 'bunch', 0),
('vn-canh-01_ing_6', 'vn-canh-01', 'CHILI', 'Ớt sừng cay', 1, 'piece', 0),
('vn-canh-01_ing_7', 'vn-canh-01', 'FISH_SAUCE', 'Nước mắm ngon', 30, 'ml', 0),
('vn-canh-01_ing_8', 'vn-canh-01', 'COOKING_OIL', 'Tỏi phi & dầu ăn', 15, 'ml', 0),
('vn-canh-02_ing_1', 'vn-canh-02', 'CRAB_MEAT', 'Cua đồng giã nhuyễn lọc lấy nước', 350, 'g', 0),
('vn-canh-02_ing_2', 'vn-canh-02', 'SPINACH', 'Rau đay & mồng tơi', 250, 'g', 0),
('vn-canh-02_ing_3', 'vn-canh-02', 'WINTER_MELON', 'Mướp hương thái vát', 1, 'piece', 0),
('vn-canh-02_ing_4', 'vn-canh-02', 'FISH_SAUCE', 'Nước mắm truyền thống', 15, 'ml', 0),
('vn-canh-02_ing_5', 'vn-canh-02', 'GARLIC', 'Hành tím khô băm nhỏ', 1, 'piece', 0),
('vn-canh-03_ing_1', 'vn-canh-03', 'BITTER_MELON', 'Mướp đắng / Khổ qua xanh', 3, 'piece', 0),
('vn-canh-03_ing_2', 'vn-canh-03', 'GROUND_PORK', 'Thịt heo nạc xay', 250, 'g', 0),
('vn-canh-03_ing_3', 'vn-canh-03', 'MUSHROOM', 'Nấm mèo / Mộc nhĩ ngâm nở', 50, 'g', 0),
('vn-canh-03_ing_4', 'vn-canh-03', 'SCALLION', 'Hành lá & ngò rí', 1, 'bunch', 0),
('vn-canh-03_ing_5', 'vn-canh-03', 'FISH_SAUCE', 'Nước mắm ngon', 20, 'ml', 0),
('vn-canh-04_ing_1', 'vn-canh-04', 'PORK_RIBS', 'Sườn non heo chặt miếng vừa', 400, 'g', 0),
('vn-canh-04_ing_2', 'vn-canh-04', 'WINTER_MELON', 'Bí đao gọt vỏ cắt miếng', 1, 'piece', 0),
('vn-canh-04_ing_3', 'vn-canh-04', 'SCALLION', 'Hành lá & mùi tàu', 1, 'bunch', 0),
('vn-canh-04_ing_4', 'vn-canh-04', 'GARLIC', 'Hành khô băm', 1, 'piece', 0),
('vn-canh-04_ing_5', 'vn-canh-04', 'FISH_SAUCE', 'Nước mắm nguyên chất', 20, 'ml', 0),
('vn-canh-05_ing_1', 'vn-canh-05', 'PUMPKIN', 'Bí đỏ gọt vỏ cắt quân cờ', 1, 'piece', 0),
('vn-canh-05_ing_2', 'vn-canh-05', 'GROUND_PORK', 'Thịt heo xay nạc', 200, 'g', 0),
('vn-canh-05_ing_3', 'vn-canh-05', 'SCALLION', 'Hành hoa & ngò gai', 1, 'bunch', 0),
('vn-canh-05_ing_4', 'vn-canh-05', 'GARLIC', 'Hành tím băm nhuyễn', 1, 'piece', 0),
('vn-canh-05_ing_5', 'vn-canh-05', 'FISH_SAUCE', 'Nước mắm ngon', 15, 'ml', 0),
('vn-canh-05_ing_6', 'vn-canh-05', 'COOKING_OIL', 'Dầu ăn thực vật', 10, 'ml', 0),
('vn-canh-06_ing_1', 'vn-canh-06', 'CRAB_MEAT', 'Ngao tươi sống / Thịt ngao', 500, 'g', 0),
('vn-canh-06_ing_2', 'vn-canh-06', 'TOMATO', 'Cà chua đỏ chín', 2, 'piece', 0),
('vn-canh-06_ing_3', 'vn-canh-06', 'PINEAPPLE', 'Dứa thơm thái mỏng', 1, 'piece', 0),
('vn-canh-06_ing_4', 'vn-canh-06', 'SCALLION', 'Hành hoa & thì là tươi', 1, 'bunch', 0),
('vn-canh-06_ing_5', 'vn-canh-06', 'CHILI', 'Ớt tươi', 1, 'piece', 0),
('vn-canh-06_ing_6', 'vn-canh-06', 'FISH_SAUCE', 'Nước mắm cốt', 15, 'ml', 0),
('vn-kho-01_ing_1', 'vn-kho-01', 'PORK_BELLY', 'Thịt ba chỉ', 400, 'g', 0),
('vn-kho-01_ing_2', 'vn-kho-01', 'CHICKEN_EGG', 'Trứng gà ta', 4, 'piece', 0),
('vn-kho-01_ing_3', 'vn-kho-01', 'GARLIC', 'Tỏi & hành tím giã nhuyễn', 1, 'piece', 0),
('vn-kho-01_ing_4', 'vn-kho-01', 'FISH_SAUCE', 'Nước mắm Phú Quốc hảo hạng', 40, 'ml', 0),
('vn-kho-01_ing_5', 'vn-kho-01', 'CHILI', 'Ớt sừng nguyên trái', 2, 'piece', 0),
('vn-kho-02_ing_1', 'vn-kho-02', 'FISH_FRESHWATER', 'Cá lóc cắt khứa dày', 500, 'g', 0),
('vn-kho-02_ing_2', 'vn-kho-02', 'PORK_BELLY', 'Thịt ba chỉ thái mỏng (lấy tóp mỡ)', 100, 'g', 1),
('vn-kho-02_ing_3', 'vn-kho-02', 'GARLIC', 'Hành tím & tỏi khô', 1, 'piece', 0),
('vn-kho-02_ing_4', 'vn-kho-02', 'FISH_SAUCE', 'Nước mắm cá cơm ngon', 40, 'ml', 0),
('vn-kho-02_ing_5', 'vn-kho-02', 'CHILI', 'Ớt hiểm cay', 2, 'piece', 0),
('vn-kho-02_ing_6', 'vn-kho-02', 'SCALLION', 'Hành lá đầu hành', 1, 'bunch', 0),
('vn-kho-03_ing_1', 'vn-kho-03', 'CHICKEN_THIGH', 'Thịt đùi gà ta chặt miếng', 500, 'g', 0),
('vn-kho-03_ing_2', 'vn-kho-03', 'GINGER', 'Gừng già cạo vỏ thái sợi', 40, 'g', 0),
('vn-kho-03_ing_3', 'vn-kho-03', 'LEMONGRASS', 'Sả tươi băm nhuyễn', 2, 'piece', 0),
('vn-kho-03_ing_4', 'vn-kho-03', 'FISH_SAUCE', 'Nước mắm ngon', 30, 'ml', 0),
('vn-kho-03_ing_5', 'vn-kho-03', 'CHILI', 'Ớt tươi cắt lát', 1, 'piece', 0),
('vn-kho-03_ing_6', 'vn-kho-03', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-kho-04_ing_1', 'vn-kho-04', 'PORK_RIBS', 'Sườn non heo chặt dẻ nhỏ', 500, 'g', 0),
('vn-kho-04_ing_2', 'vn-kho-04', 'TOMATO', 'Cà chua chín băm nhỏ', 2, 'piece', 0),
('vn-kho-04_ing_3', 'vn-kho-04', 'ONION', 'Hành tây thái múi cau', 1, 'piece', 0),
('vn-kho-04_ing_4', 'vn-kho-04', 'GARLIC', 'Tỏi băm nhuyễn', 1, 'piece', 0),
('vn-kho-04_ing_5', 'vn-kho-04', 'FISH_SAUCE', 'Nước mắm ngon', 25, 'ml', 0),
('vn-kho-04_ing_6', 'vn-kho-04', 'COOKING_OIL', 'Dầu ăn để rán sườn', 30, 'ml', 0),
('vn-kho-05_ing_1', 'vn-kho-05', 'SHRIMP', 'Tôm tươi cắt bớt râu chân', 350, 'g', 0),
('vn-kho-05_ing_2', 'vn-kho-05', 'GARLIC', 'Tỏi & hành khô băm nhỏ', 1, 'piece', 0),
('vn-kho-05_ing_3', 'vn-kho-05', 'SCALLION', 'Hành hoa thái nhỏ', 1, 'bunch', 0),
('vn-kho-05_ing_4', 'vn-kho-05', 'FISH_SAUCE', 'Nước mắm truyền thống', 25, 'ml', 0),
('vn-kho-05_ing_5', 'vn-kho-05', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-kho-06_ing_1', 'vn-kho-06', 'PORK_BELLY', 'Thịt ba chỉ heo', 400, 'g', 0),
('vn-kho-06_ing_2', 'vn-kho-06', 'CARROT', 'Củ cải trắng (cắt khúc vuông)', 2, 'piece', 0),
('vn-kho-06_ing_3', 'vn-kho-06', 'GARLIC', 'Hành tím băm', 1, 'piece', 0),
('vn-kho-06_ing_4', 'vn-kho-06', 'FISH_SAUCE', 'Nước mắm ngon', 30, 'ml', 0),
('vn-kho-06_ing_5', 'vn-kho-06', 'CHILI', 'Ớt tươi', 1, 'piece', 0),
('vn-xao-01_ing_1', 'vn-xao-01', 'WATER_SPINACH', 'Rau muống ngọn non nhặt sạch', 1, 'bunch', 0),
('vn-xao-01_ing_2', 'vn-xao-01', 'GARLIC', 'Tỏi ta đập dập nguyên tép', 2, 'piece', 0),
('vn-xao-01_ing_3', 'vn-xao-01', 'COOKING_OIL', 'Dầu ăn', 20, 'ml', 0),
('vn-xao-01_ing_4', 'vn-xao-01', 'FISH_SAUCE', 'Nước mắm ngon', 15, 'ml', 0),
('vn-xao-02_ing_1', 'vn-xao-02', 'BEEF_SIRLOIN', 'Thịt bò thăn thái lát mỏng ngang thớ', 300, 'g', 0),
('vn-xao-02_ing_2', 'vn-xao-02', 'ONION', 'Hành tây thái múi cau', 1, 'piece', 0),
('vn-xao-02_ing_3', 'vn-xao-02', 'TOMATO', 'Cà chua thái múi', 1, 'piece', 0),
('vn-xao-02_ing_4', 'vn-xao-02', 'GARLIC', 'Tỏi khô băm nhỏ', 1, 'piece', 0),
('vn-xao-02_ing_5', 'vn-xao-02', 'COOKING_OIL', 'Dầu ăn', 20, 'ml', 0),
('vn-xao-02_ing_6', 'vn-xao-02', 'SOY_SAUCE', 'Xì dầu / Nước tương', 15, 'ml', 0),
('vn-xao-03_ing_1', 'vn-xao-03', 'SQUID', 'Mực ống tươi khứa vảy rồng', 400, 'g', 0),
('vn-xao-03_ing_2', 'vn-xao-03', 'PINEAPPLE', 'Dứa thái lát mỏng', 1, 'piece', 0),
('vn-xao-03_ing_3', 'vn-xao-03', 'TOMATO', 'Cà chua chín', 1, 'piece', 0),
('vn-xao-03_ing_4', 'vn-xao-03', 'ONION', 'Hành tây', 1, 'piece', 0),
('vn-xao-03_ing_5', 'vn-xao-03', 'GARLIC', 'Tỏi & gừng băm', 1, 'piece', 0),
('vn-xao-03_ing_6', 'vn-xao-03', 'FISH_SAUCE', 'Nước mắm ngon', 20, 'ml', 0),
('vn-xao-04_ing_1', 'vn-xao-04', 'BEEF_SIRLOIN', 'Thịt bò mềm thái lát', 250, 'g', 0),
('vn-xao-04_ing_2', 'vn-xao-04', 'BROCCOLI', 'Bông cải xanh cắt miếng', 1, 'piece', 0),
('vn-xao-04_ing_3', 'vn-xao-04', 'CARROT', 'Cà rốt tỉa hoa thái mỏng', 1, 'piece', 0),
('vn-xao-04_ing_4', 'vn-xao-04', 'GARLIC', 'Tỏi băm', 1, 'piece', 0),
('vn-xao-04_ing_5', 'vn-xao-04', 'SOY_SAUCE', 'Dầu hào & xì dầu', 20, 'ml', 0),
('vn-xao-04_ing_6', 'vn-xao-04', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-xao-05_ing_1', 'vn-xao-05', 'CHAYOTE', 'Quả su su non bào sợi', 2, 'piece', 0),
('vn-xao-05_ing_2', 'vn-xao-05', 'CHICKEN_EGG', 'Trứng gà', 2, 'piece', 0),
('vn-xao-05_ing_3', 'vn-xao-05', 'SCALLION', 'Hành hoa thái nhỏ', 1, 'bunch', 0),
('vn-xao-05_ing_4', 'vn-xao-05', 'GARLIC', 'Hành tím băm', 1, 'piece', 0),
('vn-xao-05_ing_5', 'vn-xao-05', 'FISH_SAUCE', 'Nước mắm ngon', 15, 'ml', 0),
('vn-xao-05_ing_6', 'vn-xao-05', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-xao-06_ing_1', 'vn-xao-06', 'BEEF_SIRLOIN', 'Thịt bò thăn', 250, 'g', 0),
('vn-xao-06_ing_2', 'vn-xao-06', 'WATER_SPINACH', 'Đậu cô ve non tước xơ', 300, 'g', 0),
('vn-xao-06_ing_3', 'vn-xao-06', 'GARLIC', 'Tỏi băm thơm', 1, 'piece', 0),
('vn-xao-06_ing_4', 'vn-xao-06', 'FISH_SAUCE', 'Nước mắm & dầu hào', 20, 'ml', 0),
('vn-xao-06_ing_5', 'vn-xao-06', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-chien-01_ing_1', 'vn-chien-01', 'TOFU', 'Đậu phụ trắng Mơ', 3, 'piece', 0),
('vn-chien-01_ing_2', 'vn-chien-01', 'TOMATO', 'Cà chua chín mọng', 3, 'piece', 0),
('vn-chien-01_ing_3', 'vn-chien-01', 'SCALLION', 'Hành lá tươi', 1, 'bunch', 0),
('vn-chien-01_ing_4', 'vn-chien-01', 'FISH_SAUCE', 'Nước mắm ngon', 20, 'ml', 0),
('vn-chien-01_ing_5', 'vn-chien-01', 'COOKING_OIL', 'Dầu ăn chiên đậu', 30, 'ml', 0),
('vn-chien-02_ing_1', 'vn-chien-02', 'CHICKEN_EGG', 'Trứng gà tươi', 4, 'piece', 0),
('vn-chien-02_ing_2', 'vn-chien-02', 'GROUND_PORK', 'Thịt heo xay nạc', 150, 'g', 0),
('vn-chien-02_ing_3', 'vn-chien-02', 'MUSHROOM', 'Nấm rơm hoặc nấm hương băm nhỏ', 50, 'g', 0),
('vn-chien-02_ing_4', 'vn-chien-02', 'SCALLION', 'Hành hoa & hành khô', 1, 'bunch', 0),
('vn-chien-02_ing_5', 'vn-chien-02', 'FISH_SAUCE', 'Nước mắm ngon', 15, 'ml', 0),
('vn-chien-02_ing_6', 'vn-chien-02', 'COOKING_OIL', 'Dầu ăn', 20, 'ml', 0),
('vn-chien-03_ing_1', 'vn-chien-03', 'CHICKEN_THIGH', 'Cánh gà khúc giữa tươi', 500, 'g', 0),
('vn-chien-03_ing_2', 'vn-chien-03', 'GARLIC', 'Tỏi ta băm nhuyễn', 2, 'piece', 0),
('vn-chien-03_ing_3', 'vn-chien-03', 'CHILI', 'Ớt sừng băm', 1, 'piece', 0),
('vn-chien-03_ing_4', 'vn-chien-03', 'FISH_SAUCE', 'Nước mắm truyền thống', 30, 'ml', 0),
('vn-chien-03_ing_5', 'vn-chien-03', 'COOKING_OIL', 'Dầu ăn chiên gà', 100, 'ml', 0),
('vn-chien-04_ing_1', 'vn-chien-04', 'FISH_FRESHWATER', 'Phi lê cá tươi quết dẻo', 450, 'g', 0),
('vn-chien-04_ing_2', 'vn-chien-04', 'PORK_BELLY', 'Mỡ heo hạt lựu (tạo độ mọng)', 80, 'g', 0),
('vn-chien-04_ing_3', 'vn-chien-04', 'SCALLION', 'Thì là tươi cắt nhỏ', 1, 'bunch', 0),
('vn-chien-04_ing_4', 'vn-chien-04', 'GARLIC', 'Hành khô băm', 1, 'piece', 0),
('vn-chien-04_ing_5', 'vn-chien-04', 'FISH_SAUCE', 'Nước mắm ngon', 20, 'ml', 0),
('vn-chien-04_ing_6', 'vn-chien-04', 'COOKING_OIL', 'Dầu ăn chiên', 60, 'ml', 0),
('vn-chien-05_ing_1', 'vn-chien-05', 'GROUND_PORK', 'Thịt heo vai xay', 300, 'g', 0),
('vn-chien-05_ing_2', 'vn-chien-05', 'SHRIMP', 'Tôm tươi băm nhỏ', 100, 'g', 1),
('vn-chien-05_ing_3', 'vn-chien-05', 'CHICKEN_EGG', 'Lòng đỏ trứng gà', 2, 'piece', 0),
('vn-chien-05_ing_4', 'vn-chien-05', 'CARROT', 'Cà rốt & củ đậu thái chỉ', 1, 'piece', 0),
('vn-chien-05_ing_5', 'vn-chien-05', 'MUSHROOM', 'Mộc nhĩ & nấm hương băm', 40, 'g', 0),
('vn-chien-05_ing_6', 'vn-chien-05', 'RICE_PAPER', 'Bánh đa nem / Bánh tráng giòn', 1, 'pack', 0),
('vn-chien-05_ing_7', 'vn-chien-05', 'COOKING_OIL', 'Dầu rán nem', 100, 'ml', 0),
('vn-chien-06_ing_1', 'vn-chien-06', 'FISH_FRESHWATER', 'Cá rô phi tươi nguyên con khía sâu', 700, 'g', 0),
('vn-chien-06_ing_2', 'vn-chien-06', 'GINGER', 'Gừng tươi giã nhuyễn', 30, 'g', 0),
('vn-chien-06_ing_3', 'vn-chien-06', 'GARLIC', 'Tỏi & ớt băm', 1, 'piece', 0),
('vn-chien-06_ing_4', 'vn-chien-06', 'LIME', 'Chanh vắt lấy nước cốt', 1, 'piece', 0),
('vn-chien-06_ing_5', 'vn-chien-06', 'FISH_SAUCE', 'Nước mắm nguyên chất', 30, 'ml', 0),
('vn-chien-06_ing_6', 'vn-chien-06', 'COOKING_OIL', 'Dầu ăn chiên cá', 80, 'ml', 0),
('vn-hap-01_ing_1', 'vn-hap-01', 'CHICKEN_THIGH', 'Gà ta nửa con hoặc đùi gà tươi', 600, 'g', 0),
('vn-hap-01_ing_2', 'vn-hap-01', 'GINGER', 'Gừng đập dập & hành củ', 30, 'g', 0),
('vn-hap-01_ing_3', 'vn-hap-01', 'LIME', 'Lá chanh tươi bánh tẻ thái chỉ', 2, 'piece', 0),
('vn-hap-01_ing_4', 'vn-hap-01', 'CHILI', 'Ớt tươi cắt lát', 1, 'piece', 0),
('vn-hap-02_ing_1', 'vn-hap-02', 'PORK_BELLY', 'Thịt ba chỉ rút sườn liền khổ', 500, 'g', 0),
('vn-hap-02_ing_2', 'vn-hap-02', 'GARLIC', 'Hành khô đập dập', 2, 'piece', 0),
('vn-hap-02_ing_3', 'vn-hap-02', 'GINGER', 'Gừng đập dập', 20, 'g', 0),
('vn-hap-02_ing_4', 'vn-hap-02', 'FISH_SAUCE', 'Nước mắm chấm hoặc mắm tôm', 30, 'ml', 0),
('vn-hap-02_ing_5', 'vn-hap-02', 'LIME', 'Chanh tươi', 1, 'piece', 0),
('vn-hap-02_ing_6', 'vn-hap-02', 'CHILI', 'Ớt cay băm nhỏ', 1, 'piece', 0),
('vn-hap-03_ing_1', 'vn-hap-03', 'FISH_FRESHWATER', 'Cá điêu hồng tươi nguyên con', 800, 'g', 0),
('vn-hap-03_ing_2', 'vn-hap-03', 'GINGER', 'Gừng non cạo vỏ thái sợi dài', 50, 'g', 0),
('vn-hap-03_ing_3', 'vn-hap-03', 'SCALLION', 'Hành hoa chẻ sợi mảnh', 1, 'bunch', 0),
('vn-hap-03_ing_4', 'vn-hap-03', 'SOY_SAUCE', 'Xì dầu hảo hạng & dầu hào', 40, 'ml', 0),
('vn-hap-03_ing_5', 'vn-hap-03', 'COOKING_OIL', 'Dầu ăn đun sôi', 25, 'ml', 0),
('vn-hap-04_ing_1', 'vn-hap-04', 'BROCCOLI', 'Súp lơ xanh cắt miếng', 1, 'piece', 0),
('vn-hap-04_ing_2', 'vn-hap-04', 'CARROT', 'Cà rốt cắt khúc', 1, 'piece', 0),
('vn-hap-04_ing_3', 'vn-hap-04', 'CHAYOTE', 'Quả su su cắt con chì', 1, 'piece', 0),
('vn-hap-04_ing_4', 'vn-hap-04', 'PORK_BELLY', 'Thịt ba chỉ thái hạt lựu (làm tóp mỡ)', 150, 'g', 0),
('vn-hap-04_ing_5', 'vn-hap-04', 'SHRIMP', 'Tôm khô ngâm mềm', 50, 'g', 0),
('vn-hap-04_ing_6', 'vn-hap-04', 'FISH_SAUCE', 'Nước mắm ngon', 40, 'ml', 0),
('vn-hap-04_ing_7', 'vn-hap-04', 'CHILI', 'Ớt hiểm & tiêu xanh', 2, 'piece', 0),
('vn-hap-05_ing_1', 'vn-hap-05', 'SQUID', 'Mực ống tươi nguyên con', 500, 'g', 0),
('vn-hap-05_ing_2', 'vn-hap-05', 'GINGER', 'Gừng non thái chỉ', 30, 'g', 0),
('vn-hap-05_ing_3', 'vn-hap-05', 'LEMONGRASS', 'Sả tươi đập dập cắt khúc', 3, 'piece', 0),
('vn-hap-05_ing_4', 'vn-hap-05', 'CHILI', 'Ớt sừng thái vát', 1, 'piece', 0),
('vn-hap-05_ing_5', 'vn-hap-05', 'LIME', 'Chanh chấm muối tiêu', 1, 'piece', 0),
('vn-hap-06_ing_1', 'vn-hap-06', 'SHRIMP', 'Tôm sú hoặc tôm càng tươi sống', 400, 'g', 0),
('vn-hap-06_ing_2', 'vn-hap-06', 'LEMONGRASS', 'Sả cây đập dập', 2, 'piece', 0),
('vn-hap-06_ing_3', 'vn-hap-06', 'LIME', 'Chanh & muối tiêu hạt', 1, 'piece', 0),
('vn-cuon-01_ing_1', 'vn-cuon-01', 'SHRIMP', 'Tôm sú tươi luộc bóc vỏ chẻ đôi', 250, 'g', 0),
('vn-cuon-01_ing_2', 'vn-cuon-01', 'PORK_BELLY', 'Thịt ba chỉ luộc thái mỏng', 200, 'g', 0),
('vn-cuon-01_ing_3', 'vn-cuon-01', 'NOODLE', 'Bún tươi sợi nhỏ', 300, 'g', 0),
('vn-cuon-01_ing_4', 'vn-cuon-01', 'RICE_PAPER', 'Bánh tráng dẻo cuốn gỏi', 1, 'pack', 0),
('vn-cuon-01_ing_5', 'vn-cuon-01', 'SCALLION', 'Hẹ lá dài & rau húng quế', 1, 'bunch', 0),
('vn-cuon-01_ing_6', 'vn-cuon-01', 'SOY_SAUCE', 'Tương đen & bơ đậu phộng', 40, 'ml', 0),
('vn-cuon-02_ing_1', 'vn-cuon-02', 'BEEF_SIRLOIN', 'Thịt bò thăn thái lát mỏng', 300, 'g', 0),
('vn-cuon-02_ing_2', 'vn-cuon-02', 'NOODLE', 'Bánh phở vuông cán phẳng', 1, 'pack', 0),
('vn-cuon-02_ing_3', 'vn-cuon-02', 'GARLIC', 'Tỏi băm thơm', 1, 'piece', 0),
('vn-cuon-02_ing_4', 'vn-cuon-02', 'SCALLION', 'Rau húng Láng & xà lách', 1, 'bunch', 0),
('vn-cuon-02_ing_5', 'vn-cuon-02', 'FISH_SAUCE', 'Nước mắm chấm chua ngọt', 30, 'ml', 0),
('vn-cuon-02_ing_6', 'vn-cuon-02', 'COOKING_OIL', 'Dầu xào bò', 15, 'ml', 0),
('vn-cuon-03_ing_1', 'vn-cuon-03', 'PORK_BELLY', 'Tai heo làm sạch luộc chín giòn', 250, 'g', 0),
('vn-cuon-03_ing_2', 'vn-cuon-03', 'CARROT', 'Cà rốt nạo sợi', 1, 'piece', 0),
('vn-cuon-03_ing_3', 'vn-cuon-03', 'BEAN_SPROUTS', 'Giá đỗ sống nhặt sạch', 100, 'g', 0),
('vn-cuon-03_ing_4', 'vn-cuon-03', 'LIME', 'Chanh tươi vắt nước cốt', 2, 'piece', 0),
('vn-cuon-03_ing_5', 'vn-cuon-03', 'CHILI', 'Ớt sừng băm & tỏi băm', 1, 'piece', 0),
('vn-cuon-03_ing_6', 'vn-cuon-03', 'FISH_SAUCE', 'Nước mắm trộn gỏi', 30, 'ml', 0),
('vn-cuon-04_ing_1', 'vn-cuon-04', 'CHICKEN_BREAST', 'Thịt gà ta luộc xé miếng vừa', 350, 'g', 0),
('vn-cuon-04_ing_2', 'vn-cuon-04', 'CABBAGE', 'Bắp cải bào sợi mỏng', 1, 'piece', 0),
('vn-cuon-04_ing_3', 'vn-cuon-04', 'ONION', 'Hành tây thái mỏng ngâm giấm đá', 1, 'piece', 0),
('vn-cuon-04_ing_4', 'vn-cuon-04', 'LIME', 'Nước cốt chanh tươi', 2, 'piece', 0),
('vn-cuon-04_ing_5', 'vn-cuon-04', 'FISH_SAUCE', 'Nước mắm trộn', 30, 'ml', 0),
('vn-cuon-04_ing_6', 'vn-cuon-04', 'CHILI', 'Ớt sừng thái sợi & tiêu', 1, 'piece', 0),
('vn-cuon-05_ing_1', 'vn-cuon-05', 'CARROT', 'Đu đủ xanh & cà rốt nạo sợi', 2, 'piece', 0),
('vn-cuon-05_ing_2', 'vn-cuon-05', 'BEEF_SIRLOIN', 'Thịt bò khô xé sợi / gan bò tẩm vị', 100, 'g', 0),
('vn-cuon-05_ing_3', 'vn-cuon-05', 'SCALLION', 'Rau kinh giới & rau húng bạc hà', 1, 'bunch', 0),
('vn-cuon-05_ing_4', 'vn-cuon-05', 'FISH_SAUCE', 'Nước mắm pha giấm đường tỏi ớt', 30, 'ml', 0),
('vn-cuon-06_ing_1', 'vn-cuon-06', 'GROUND_PORK', 'Thịt heo xay có mỡ dẻo', 400, 'g', 0),
('vn-cuon-06_ing_2', 'vn-cuon-06', 'LEMONGRASS', 'Cây sả tươi làm que lụi', 8, 'piece', 0),
('vn-cuon-06_ing_3', 'vn-cuon-06', 'GARLIC', 'Hành tím & tỏi băm nhuyễn', 1, 'piece', 0),
('vn-cuon-06_ing_4', 'vn-cuon-06', 'FISH_SAUCE', 'Nước mắm ngon & mật ong', 25, 'ml', 0),
('vn-cuon-06_ing_5', 'vn-cuon-06', 'RICE_PAPER', 'Bánh tráng cuốn nem', 1, 'pack', 0),
('vn-cuon-06_ing_6', 'vn-cuon-06', 'CUCUMBER', 'Dưa chuột & chuối chát', 1, 'piece', 0),
('vn-bun-01_ing_1', 'vn-bun-01', 'BEEF_SIRLOIN', 'Thịt bò bắp / thăn mềm', 400, 'g', 0),
('vn-bun-01_ing_2', 'vn-bun-01', 'NOODLE', 'Bánh phở tươi sợi mềm', 500, 'g', 0),
('vn-bun-01_ing_3', 'vn-bun-01', 'GINGER', 'Gừng nướng thơm & hoa hồi quế', 30, 'g', 0),
('vn-bun-01_ing_4', 'vn-bun-01', 'ONION', 'Hành tây & hành củ nướng', 1, 'piece', 0),
('vn-bun-01_ing_5', 'vn-bun-01', 'SCALLION', 'Hành hoa & ngò gai thái nhỏ', 1, 'bunch', 0),
('vn-bun-01_ing_6', 'vn-bun-01', 'FISH_SAUCE', 'Nước mắm truyền thống', 30, 'ml', 0),
('vn-bun-02_ing_1', 'vn-bun-02', 'PORK_BELLY', 'Thịt ba chỉ thái miếng mỏng', 300, 'g', 0),
('vn-bun-02_ing_2', 'vn-bun-02', 'GROUND_PORK', 'Thịt nạc vai xay làm chả viên', 250, 'g', 0),
('vn-bun-02_ing_3', 'vn-bun-02', 'NOODLE', 'Bún tươi lá hoặc sợi rối', 500, 'g', 0),
('vn-bun-02_ing_4', 'vn-bun-02', 'GARLIC', 'Hành tím & sả băm vắt lấy nước cốt', 1, 'piece', 0),
('vn-bun-02_ing_5', 'vn-bun-02', 'CARROT', 'Đu đủ & cà rốt làm dưa góp', 1, 'piece', 0),
('vn-bun-02_ing_6', 'vn-bun-02', 'FISH_SAUCE', 'Nước mắm pha nước chấm', 45, 'ml', 0),
('vn-bun-03_ing_1', 'vn-bun-03', 'BEEF_SIRLOIN', 'Bắp bò hoa luộc thái lát', 350, 'g', 0),
('vn-bun-03_ing_2', 'vn-bun-03', 'PORK_RIBS', 'Giò heo / xương ống ninh nước dùng', 400, 'g', 0),
('vn-bun-03_ing_3', 'vn-bun-03', 'NOODLE', 'Bún sợi to cọng tròn Huế', 500, 'g', 0),
('vn-bun-03_ing_4', 'vn-bun-03', 'LEMONGRASS', 'Sả cây đập dập bó lọn', 4, 'piece', 0),
('vn-bun-03_ing_5', 'vn-bun-03', 'CHILI', 'Ớt bột Sa Tế cay nồng', 2, 'piece', 0),
('vn-bun-03_ing_6', 'vn-bun-03', 'SCALLION', 'Hành tây thái mỏng & rau mùi', 1, 'bunch', 0),
('vn-bun-04_ing_1', 'vn-bun-04', 'CRAB_MEAT', 'Cua đồng xay lọc lấy nước riêu', 400, 'g', 0),
('vn-bun-04_ing_2', 'vn-bun-04', 'TOFU', 'Đậu phụ rán vàng giòn', 2, 'piece', 0),
('vn-bun-04_ing_3', 'vn-bun-04', 'TOMATO', 'Cà chua bổ múi cau', 3, 'piece', 0),
('vn-bun-04_ing_4', 'vn-bun-04', 'BEEF_SIRLOIN', 'Thịt bò tái chần mềm', 200, 'g', 1),
('vn-bun-04_ing_5', 'vn-bun-04', 'NOODLE', 'Bún tươi sợi nhỏ', 500, 'g', 0),
('vn-bun-04_ing_6', 'vn-bun-04', 'SCALLION', 'Hành hoa & kinh giới tía tô', 1, 'bunch', 0),
('vn-bun-05_ing_1', 'vn-bun-05', 'PORK_BELLY', 'Thịt ba rọi / nạc dăm ướp nướng', 400, 'g', 0),
('vn-bun-05_ing_2', 'vn-bun-05', 'NOODLE', 'Bún tươi', 500, 'g', 0),
('vn-bun-05_ing_3', 'vn-bun-05', 'SCALLION', 'Hành lá làm mỡ hành', 1, 'bunch', 0),
('vn-bun-05_ing_4', 'vn-bun-05', 'CUCUMBER', 'Dưa leo băm & xà lách rau thơm', 2, 'piece', 0),
('vn-bun-05_ing_5', 'vn-bun-05', 'FISH_SAUCE', 'Nước mắm tỏi ớt chua ngọt', 40, 'ml', 0),
('vn-bun-05_ing_6', 'vn-bun-05', 'CARROT', 'Đồ chua củ cải cà rốt', 1, 'piece', 0),
('vn-bun-06_ing_1', 'vn-bun-06', 'CHICKEN_THIGH', 'Thịt gà luộc xé miếng', 350, 'g', 0),
('vn-bun-06_ing_2', 'vn-bun-06', 'NOODLE', 'Miến dong làng So ngâm mềm', 250, 'g', 0),
('vn-bun-06_ing_3', 'vn-bun-06', 'MUSHROOM', 'Nấm hương rừng ngâm nở', 40, 'g', 0),
('vn-bun-06_ing_4', 'vn-bun-06', 'SCALLION', 'Hành hoa & rau răm thái nhỏ', 1, 'bunch', 0),
('vn-bun-06_ing_5', 'vn-bun-06', 'FISH_SAUCE', 'Nước mắm ngon', 20, 'ml', 0),
('vn-chay-01_ing_1', 'vn-chay-01', 'TOFU', 'Đậu phụ cắt miếng chiên vàng', 3, 'piece', 0),
('vn-chay-01_ing_2', 'vn-chay-01', 'MUSHROOM', 'Nấm đông cô / nấm đùi gà', 150, 'g', 0),
('vn-chay-01_ing_3', 'vn-chay-01', 'SOY_SAUCE', 'Nước tương ngon & dầu hào chay', 30, 'ml', 0),
('vn-chay-01_ing_4', 'vn-chay-01', 'CHILI', 'Ớt tươi & tiêu đen đập dập', 1, 'piece', 0),
('vn-chay-01_ing_5', 'vn-chay-01', 'COOKING_OIL', 'Dầu mè & dầu ăn', 15, 'ml', 0),
('vn-chay-02_ing_1', 'vn-chay-02', 'MUSHROOM', 'Nấm đùi gà & nấm kim châm', 200, 'g', 0),
('vn-chay-02_ing_2', 'vn-chay-02', 'CARROT', 'Cà rốt tỉa hoa', 1, 'piece', 0),
('vn-chay-02_ing_3', 'vn-chay-02', 'WINTER_MELON', 'Bắp ngọt & củ sen thái lát', 1, 'piece', 0),
('vn-chay-02_ing_4', 'vn-chay-02', 'SCALLION', 'Mùi tàu & boa-rô', 1, 'bunch', 0),
('vn-chay-02_ing_5', 'vn-chay-02', 'SOY_SAUCE', 'Muối hột & hạt nêm chay', 15, 'ml', 0),
('vn-chay-03_ing_1', 'vn-chay-03', 'NOODLE', 'Mì sợi vàng / mì gói chần sơ', 200, 'g', 0),
('vn-chay-03_ing_2', 'vn-chay-03', 'MUSHROOM', 'Nấm đùi gà thái lát mỏng', 150, 'g', 0),
('vn-chay-03_ing_3', 'vn-chay-03', 'CARROT', 'Cà rốt thái sợi', 1, 'piece', 0),
('vn-chay-03_ing_4', 'vn-chay-03', 'CABBAGE', 'Cải ngọt / bắp cải', 1, 'piece', 0),
('vn-chay-03_ing_5', 'vn-chay-03', 'SOY_SAUCE', 'Xì dầu & dầu hào chay', 25, 'ml', 0),
('vn-chay-03_ing_6', 'vn-chay-03', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-chay-04_ing_1', 'vn-chay-04', 'BITTER_MELON', 'Cà tím dài quả thẳng', 2, 'piece', 0),
('vn-chay-04_ing_2', 'vn-chay-04', 'SCALLION', 'Hành hoa thái nhỏ', 1, 'bunch', 0),
('vn-chay-04_ing_3', 'vn-chay-04', 'CHILI', 'Ớt tươi băm nhuyễn', 1, 'piece', 0),
('vn-chay-04_ing_4', 'vn-chay-04', 'GARLIC', 'Tỏi băm nhỏ', 1, 'piece', 0),
('vn-chay-04_ing_5', 'vn-chay-04', 'SOY_SAUCE', 'Nước tương hảo hạng', 30, 'ml', 0),
('vn-chay-04_ing_6', 'vn-chay-04', 'COOKING_OIL', 'Dầu ăn làm mỡ hành', 25, 'ml', 0),
('vn-chay-05_ing_1', 'vn-chay-05', 'TOFU', 'Đậu hũ non cây cắt khoanh tròn', 2, 'piece', 0),
('vn-chay-05_ing_2', 'vn-chay-05', 'MUSHROOM', 'Nấm rơm tươi cắt đôi', 150, 'g', 0),
('vn-chay-05_ing_3', 'vn-chay-05', 'SCALLION', 'Hành hoa & ngò rí', 1, 'bunch', 0),
('vn-chay-05_ing_4', 'vn-chay-05', 'SOY_SAUCE', 'Dầu hào chay & xì dầu', 25, 'ml', 0),
('vn-chay-05_ing_5', 'vn-chay-05', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('vn-chay-06_ing_1', 'vn-chay-06', 'WATER_SPINACH', 'Rau cải bẹ xanh cắt khúc', 1, 'bunch', 0),
('vn-chay-06_ing_2', 'vn-chay-06', 'TOFU', 'Đậu phụ trắng cắt miếng vuông', 2, 'piece', 0),
('vn-chay-06_ing_3', 'vn-chay-06', 'GINGER', 'Gừng già đập dập thơm cay', 25, 'g', 0),
('vn-chay-06_ing_4', 'vn-chay-06', 'SOY_SAUCE', 'Muối hột & hạt nêm chay', 15, 'ml', 0),
('vn-sang-01_ing_1', 'vn-sang-01', 'RICE', 'Cơm nguội tơi xốp', 300, 'g', 0),
('vn-sang-01_ing_2', 'vn-sang-01', 'CHICKEN_EGG', 'Trứng gà tươi', 2, 'piece', 0),
('vn-sang-01_ing_3', 'vn-sang-01', 'GARLIC', 'Tỏi băm nhiều phi giòn', 2, 'piece', 0),
('vn-sang-01_ing_4', 'vn-sang-01', 'SCALLION', 'Hành hoa thái nhỏ', 1, 'bunch', 0),
('vn-sang-01_ing_5', 'vn-sang-01', 'FISH_SAUCE', 'Nước mắm ngon', 15, 'ml', 0),
('vn-sang-01_ing_6', 'vn-sang-01', 'COOKING_OIL', 'Dầu ăn', 20, 'ml', 0),
('vn-sang-02_ing_1', 'vn-sang-02', 'CHICKEN_EGG', 'Trứng gà ốp la lòng đào', 2, 'piece', 0),
('vn-sang-02_ing_2', 'vn-sang-02', 'CUCUMBER', 'Dưa leo thái lát mỏng', 1, 'piece', 0),
('vn-sang-02_ing_3', 'vn-sang-02', 'SCALLION', 'Rau mùi tươi', 1, 'bunch', 0),
('vn-sang-02_ing_4', 'vn-sang-02', 'SOY_SAUCE', 'Xì dầu & tương ớt', 15, 'ml', 0),
('vn-sang-02_ing_5', 'vn-sang-02', 'BUTTER', 'Bơ thực vật chiên trứng', 15, 'g', 0),
('vn-sang-03_ing_1', 'vn-sang-03', 'RICE', 'Gạo tẻ trộn chút nếp rang vàng', 150, 'g', 0),
('vn-sang-03_ing_2', 'vn-sang-03', 'GROUND_PORK', 'Thịt heo nạc băm nhỏ', 200, 'g', 0),
('vn-sang-03_ing_3', 'vn-sang-03', 'GINGER', 'Gừng già thái chỉ', 25, 'g', 0),
('vn-sang-03_ing_4', 'vn-sang-03', 'SCALLION', 'Hành hoa & lá tía tô thái sợi', 1, 'bunch', 0),
('vn-sang-03_ing_5', 'vn-sang-03', 'FISH_SAUCE', 'Nước mắm ngon & tiêu', 20, 'ml', 0),
('vn-sang-04_ing_1', 'vn-sang-04', 'NOODLE', 'Gói mì ăn liền hảo hạng', 2, 'pack', 0),
('vn-sang-04_ing_2', 'vn-sang-04', 'BEEF_SIRLOIN', 'Thịt bò thăn thái mỏng', 200, 'g', 0),
('vn-sang-04_ing_3', 'vn-sang-04', 'CHICKEN_EGG', 'Trứng gà ốp la', 2, 'piece', 0),
('vn-sang-04_ing_4', 'vn-sang-04', 'WATER_SPINACH', 'Rau cải ngọt / rau muống', 150, 'g', 0),
('vn-sang-04_ing_5', 'vn-sang-04', 'GARLIC', 'Tỏi băm thơm', 1, 'piece', 0),
('vn-sang-04_ing_6', 'vn-sang-04', 'COOKING_OIL', 'Dầu ăn', 20, 'ml', 0),
('vn-sang-05_ing_1', 'vn-sang-05', 'CHICKEN_EGG', 'Trứng gà tươi', 4, 'piece', 0),
('vn-sang-05_ing_2', 'vn-sang-05', 'CARROT', 'Cà rốt băm hạt lựu nhỏ li ti', 1, 'piece', 0),
('vn-sang-05_ing_3', 'vn-sang-05', 'SCALLION', 'Hành lá băm nhỏ', 1, 'bunch', 0),
('vn-sang-05_ing_4', 'vn-sang-05', 'FRESH_MILK', 'Sữa tươi không đường (làm mềm trứng)', 20, 'ml', 0),
('vn-sang-05_ing_5', 'vn-sang-05', 'COOKING_OIL', 'Dầu ăn tráng chảo', 10, 'ml', 0),
('vn-sang-06_ing_1', 'vn-sang-06', 'CHICKEN_BREAST', 'Ức gà ta luộc xé sợi nhỏ', 250, 'g', 0),
('vn-sang-06_ing_2', 'vn-sang-06', 'CHICKEN_EGG', 'Trứng gà đánh tan tạo vân', 1, 'piece', 0),
('vn-sang-06_ing_3', 'vn-sang-06', 'MUSHROOM', 'Nấm hương ngâm nở thái chỉ', 40, 'g', 0),
('vn-sang-06_ing_4', 'vn-sang-06', 'SCALLION', 'Rau mùi & hành lá', 1, 'bunch', 0),
('vn-sang-06_ing_5', 'vn-sang-06', 'FISH_SAUCE', 'Hạt nêm & tiêu trắng', 15, 'ml', 0),
('vn-lau-01_ing_1', 'vn-lau-01', 'CRAB_MEAT', 'Cua đồng tươi giã nhuyễn lọc lấy riêu', 600, 'g', 0),
('vn-lau-01_ing_2', 'vn-lau-01', 'BEEF_SIRLOIN', 'Bắp bò hoa thái lát mỏng nhúng lẩu', 400, 'g', 0),
('vn-lau-01_ing_3', 'vn-lau-01', 'PORK_RIBS', 'Sườn sụn heo chần sơ chặt nhỏ', 400, 'g', 0),
('vn-lau-01_ing_4', 'vn-lau-01', 'TOFU', 'Đậu phụ rán giòn phồng', 4, 'piece', 0),
('vn-lau-01_ing_5', 'vn-lau-01', 'TOMATO', 'Cà chua chín bổ múi cau', 4, 'piece', 0),
('vn-lau-01_ing_6', 'vn-lau-01', 'NOODLE', 'Bún tươi ăn kèm', 600, 'g', 0),
('vn-lau-01_ing_7', 'vn-lau-01', 'WATER_SPINACH', 'Rau muống chẻ & hoa chuối bào', 1, 'bunch', 0),
('vn-lau-02_ing_1', 'vn-lau-02', 'CHICKEN_THIGH', 'Gà ta nguyên con chặt miếng', 1000, 'g', 0),
('vn-lau-02_ing_2', 'vn-lau-02', 'LEMONGRASS', 'Sả tươi đập dập & tỏi băm', 4, 'piece', 0),
('vn-lau-02_ing_3', 'vn-lau-02', 'CHILI', 'Ớt hiểm đập dập', 3, 'piece', 0),
('vn-lau-02_ing_4', 'vn-lau-02', 'SCALLION', 'Ngò gai & ngò ôm', 1, 'bunch', 0),
('vn-lau-02_ing_5', 'vn-lau-02', 'NOODLE', 'Bún tươi sợi nhỏ', 500, 'g', 0),
('vn-lau-02_ing_6', 'vn-lau-02', 'FISH_SAUCE', 'Nước mắm cá cơm ngon', 40, 'ml', 0),
('vn-lau-03_ing_1', 'vn-lau-03', 'SHRIMP', 'Tôm sú tươi sống', 400, 'g', 0),
('vn-lau-03_ing_2', 'vn-lau-03', 'SQUID', 'Mực ống khía vảy rồng cắt khoanh', 400, 'g', 0),
('vn-lau-03_ing_3', 'vn-lau-03', 'FISH_FRESHWATER', 'Phi lê cá tươi thái lát', 300, 'g', 0),
('vn-lau-03_ing_4', 'vn-lau-03', 'MUSHROOM', 'Nấm kim châm & nấm đùi gà', 250, 'g', 0),
('vn-lau-03_ing_5', 'vn-lau-03', 'TOMATO', 'Cà chua & dứa thơm', 2, 'piece', 0),
('vn-lau-03_ing_6', 'vn-lau-03', 'LEMONGRASS', 'Sả cây & lá chanh tươi', 4, 'piece', 0),
('vn-lau-03_ing_7', 'vn-lau-03', 'NOODLE', 'Mì tôm hoặc bún tươi', 400, 'g', 0),
('vn-lau-04_ing_1', 'vn-lau-04', 'CHICKEN_THIGH', 'Gà ta thả vườn chặt miếng nhỏ', 800, 'g', 0),
('vn-lau-04_ing_2', 'vn-lau-04', 'MUSHROOM', 'Thập cẩm nấm (đùi gà, kim châm, hương)', 400, 'g', 0),
('vn-lau-04_ing_3', 'vn-lau-04', 'CARROT', 'Cà rốt & bắp ngọt', 2, 'piece', 0),
('vn-lau-04_ing_4', 'vn-lau-04', 'TOFU', 'Đậu phụ non thái lát', 2, 'piece', 0),
('vn-lau-04_ing_5', 'vn-lau-04', 'NOODLE', 'Mì trứng sợi tươi', 400, 'g', 0),
('vn-lau-05_ing_1', 'vn-lau-05', 'FISH_FRESHWATER', 'Cá thác lác nạo quết dẻo', 400, 'g', 0),
('vn-lau-05_ing_2', 'vn-lau-05', 'BITTER_MELON', 'Khổ qua bào mỏng ướp đá lạnh', 3, 'piece', 0),
('vn-lau-05_ing_3', 'vn-lau-05', 'SCALLION', 'Hành hoa & thì là thái nhỏ', 1, 'bunch', 0),
('vn-lau-05_ing_4', 'vn-lau-05', 'FISH_SAUCE', 'Nước mắm ngon & tiêu sọ trắng', 30, 'ml', 0),
('vn-lau-05_ing_5', 'vn-lau-05', 'NOODLE', 'Bún tươi sợi nhỏ', 400, 'g', 0)
ON CONFLICT(id) DO UPDATE SET
  recipe_id = excluded.recipe_id,
  ingredient_id = excluded.ingredient_id,
  name = excluded.name,
  required_quantity = excluded.required_quantity,
  unit = excluded.unit,
  is_optional = excluded.is_optional;

-- 4. Seed Recipe Steps
INSERT INTO recipe_steps (id, recipe_id, step_number, instruction, tip, timer_minutes) VALUES
('vn-canh-01_step_1', 'vn-canh-01', 1, 'Cá lóc làm sạch, xát muối và rượu trắng để khử nhớt và mùi tanh, ướp với chút nước mắm, tiêu trong 10 phút.', 'Khử tanh cá bằng muối hột và nước cốt chanh giúp cá thơm và thịt săn.', NULL),
('vn-canh-01_step_2', 'vn-canh-01', 2, 'Phi thơm tỏi băm với chút dầu ăn, cho cà chua và dứa vào xào sơ để lên màu đẹp và tạo vị chua ngọt tự nhiên.', NULL, NULL),
('vn-canh-01_step_3', 'vn-canh-01', 3, 'Đổ 1 lít nước vào nồi đun sôi, chắt nước cốt me chua vào, thả cá khúc vào nấu sôi 8 phút với lửa vừa.', NULL, 8),
('vn-canh-01_step_4', 'vn-canh-01', 4, 'Vớt bọt thường xuyên để nước canh trong. Cho giá đỗ vào đun sôi thêm 2 phút rồi tắt bếp.', NULL, 2),
('vn-canh-01_step_5', 'vn-canh-01', 5, 'Múc canh ra bát lớn, rắc ngò gai, ngò ôm cắt nhỏ, vài lát ớt và tỏi phi vàng thơm lừng lên trên.', NULL, NULL),
('vn-canh-02_step_1', 'vn-canh-02', 1, 'Nước lọc cua đồng khuấy đều cùng 1 thìa cà phê muối, bắc lên bếp đun với lửa vừa và khuấy nhẹ tay theo một chiều.', NULL, NULL),
('vn-canh-02_step_2', 'vn-canh-02', 2, 'Khi nước canh bắt đầu nóng lăn tăn, hạ lửa thật nhỏ để thịt cua kết lại thành mảng riêu nổi lên mặt.', 'Không khuấy mạnh khi nước gần sôi kẻo làm vỡ mảng gạch cua.', NULL),
('vn-canh-02_step_3', 'vn-canh-02', 3, 'Gạt nhẹ mảng thịt cua sang một bên, thả mướp hương và rau đay, mồng tơi đã rửa sạch cắt khúc vào nồi.', NULL, 3),
('vn-canh-02_step_4', 'vn-canh-02', 4, 'Nêm nước mắm vừa ăn, đun sôi bùng lại 2 phút là rau chín mềm giữ màu xanh mướt.', NULL, 2),
('vn-canh-02_step_5', 'vn-canh-02', 5, 'Múc canh ra bát, khéo léo để tảng riêu cua lên trên, ăn kèm cà pháo muối giòn.', NULL, NULL),
('vn-canh-03_step_1', 'vn-canh-03', 1, 'Khổ qua rửa sạch, rạch một đường dọc thân móc bỏ ruột, chần sơ qua nước sôi 1 phút rồi ngâm nước đá để giảm đắng.', NULL, NULL),
('vn-canh-03_step_2', 'vn-canh-03', 2, 'Trộn thịt xay, mộc nhĩ băm nhỏ, hành tím, nước mắm, tiêu xay thật đều, để 10 phút cho ngấm gia vị.', NULL, NULL),
('vn-canh-03_step_3', 'vn-canh-03', 3, 'Nhồi nhân thịt vào từng trái khổ qua, dùng cọng hành lá trần buộc nhẹ quanh quả để giữ nhân.', NULL, NULL),
('vn-canh-03_step_4', 'vn-canh-03', 4, 'Đun sôi 1 lít nước dùng, thả khổ qua nhồi thịt vào hầm nhỏ lửa trong 20 phút đến khi khổ qua mềm.', NULL, 20),
('vn-canh-03_step_5', 'vn-canh-03', 5, 'Nêm nếm lại vừa miệng, rắc hành ngò thái nhỏ và tiêu hạt đập dập lên trên.', NULL, NULL),
('vn-canh-04_step_1', 'vn-canh-04', 1, 'Sườn non chặt khúc 3cm, chần qua nước sôi cùng chút muối để loại bỏ bọt bẩn, rửa sạch lại.', NULL, NULL),
('vn-canh-04_step_2', 'vn-canh-04', 2, 'Phi thơm hành củ băm, cho sườn vào xào săn với 1 thìa nước mắm.', NULL, NULL),
('vn-canh-04_step_3', 'vn-canh-04', 3, 'Thêm 1.2 lít nước vào nồi, hầm lửa nhỏ liu riu trong 20 phút cho sườn mềm nhừ.', NULL, 20),
('vn-canh-04_step_4', 'vn-canh-04', 4, 'Cho bí đao vào nấu thêm 5 phút đến khi bí trong là chín tới, giữ được độ giòn ngọt.', NULL, 5),
('vn-canh-04_step_5', 'vn-canh-04', 5, 'Tắt bếp, thêm hành hoa mùi tàu thái nhỏ và rắc chút tiêu cay nồng.', NULL, NULL),
('vn-canh-05_step_1', 'vn-canh-05', 1, 'Thịt bằm ướp 1 thìa cà phê nước mắm, hành tím băm và chút tiêu bột trong 5 phút.', NULL, NULL),
('vn-canh-05_step_2', 'vn-canh-05', 2, 'Đặt nồi lên bếp, phi thơm hành tím với chút dầu ăn rồi trút thịt vào xào tơi săn lại.', NULL, NULL),
('vn-canh-05_step_3', 'vn-canh-05', 3, 'Đổ 800ml nước vào đun sôi, thả bí đỏ vào nấu sôi vừa trong 10 phút cho bí chín mềm bùi.', NULL, 10),
('vn-canh-05_step_4', 'vn-canh-05', 4, 'Nêm lại gia vị cho vừa miệng, dùng muôi dầm nhẹ vài miếng bí để nước canh có độ sánh vàng đẹp mắt.', NULL, NULL),
('vn-canh-05_step_5', 'vn-canh-05', 5, 'Múc canh ra tô, rắc ngò gai thái sợi lên trên và thưởng thức nóng.', NULL, NULL),
('vn-canh-06_step_1', 'vn-canh-06', 1, 'Ngao ngâm nước vo gạo và ớt cắt lát 30 phút cho nhả sạch cát, rửa sạch vỏ.', NULL, NULL),
('vn-canh-06_step_2', 'vn-canh-06', 2, 'Luộc ngao với 800ml nước đến khi ngao vừa há miệng thì vớt ra, gỡ lấy thịt, gạn lấy nước luộc trong.', NULL, 5),
('vn-canh-06_step_3', 'vn-canh-06', 3, 'Phi thơm hành củ, xào cà chua cho nhuyễn rồi trút thịt ngao vào đảo nhanh tay cùng 1 thìa nước mắm.', NULL, NULL),
('vn-canh-06_step_4', 'vn-canh-06', 4, 'Đổ nước luộc ngao và dứa vào nồi đun sôi bùng, nêm nếm lại vừa vị chua thanh ngọt.', NULL, 4),
('vn-canh-06_step_5', 'vn-canh-06', 5, 'Cho hành hoa, thì là cắt khúc vào nồi rồi tắt bếp ngay để giữ màu xanh và hương thơm thì là.', NULL, NULL),
('vn-kho-01_step_1', 'vn-kho-01', 1, 'Thịt ba chỉ cạo sạch bì, cắt miếng vuông lớn 4x4cm, chần sơ nước sôi rồi để ráo.', NULL, NULL),
('vn-kho-01_step_2', 'vn-kho-01', 2, 'Ướp thịt với nước mắm ngon, hành tỏi băm, tiêu và 1 thìa đường trong 30 phút cho ngấm sâu.', 'Ướp thịt với chút nước cốt chanh giúp phần mỡ khi kho trong veo và giòn.', NULL),
('vn-kho-01_step_3', 'vn-kho-01', 3, 'Luộc trứng gà chín tới, ngâm nước lạnh bóc sạch vỏ.', NULL, 8),
('vn-kho-01_step_4', 'vn-kho-01', 4, 'Đảo săn thịt rồi đổ nước dừa xiêm ngập mặt thịt, đun sôi rồi hạ lửa nhỏ liu riu không đậy nắp trong 30 phút.', NULL, 30),
('vn-kho-01_step_5', 'vn-kho-01', 5, 'Thả trứng luộc vào kho cùng thêm 15 phút đến khi nước thịt sánh kẹo, màu vàng ươm cánh gián đẹp mắt.', NULL, 15),
('vn-kho-02_step_1', 'vn-kho-02', 1, 'Cá lóc làm sạch ruột, xát muối khử tanh rồi ướp nước mắm, nước màu dừa, tiêu đen đập dập 20 phút.', NULL, NULL),
('vn-kho-02_step_2', 'vn-kho-02', 2, 'Cho thịt ba chỉ vào nồi đất đảo lấy mỡ giòn, phi thơm hành tím và đầu hành lá.', NULL, NULL),
('vn-kho-02_step_3', 'vn-kho-02', 3, 'Xếp từng khứa cá vào tộ đất, đun lửa lớn 3 phút cho miếng cá săn chắc hai mặt.', NULL, NULL),
('vn-kho-02_step_4', 'vn-kho-02', 4, 'Thêm nửa chén nước sôi ấm và vài trái ớt hiểm, đậy nắp kho liu riu nhỏ lửa 20 phút.', NULL, 20),
('vn-kho-02_step_5', 'vn-kho-02', 5, 'Mở nắp, rưới nước sốt lên mặt cá đến khi cạn sánh sệt, rắc nhiều tiêu đen xay và hành lá ăn kèm cơm cháy.', NULL, NULL),
('vn-kho-03_step_1', 'vn-kho-03', 1, 'Gà chặt miếng vừa ăn, chần qua nước sôi gừng để sạch mùi hôi lông, để ráo.', NULL, NULL),
('vn-kho-03_step_2', 'vn-kho-03', 2, 'Ướp thịt gà cùng nước mắm, nửa lượng gừng sợi, chút tiêu và đường trong 15 phút.', NULL, NULL),
('vn-kho-03_step_3', 'vn-kho-03', 3, 'Đun nóng dầu ăn, phi vàng thơm sả băm và phần gừng sợi còn lại.', NULL, NULL),
('vn-kho-03_step_4', 'vn-kho-03', 4, 'Cho thịt gà vào đảo đều tay trên lửa lớn cho miếng gà săn chắc và ngấm vị vàng thơm.', NULL, 5),
('vn-kho-03_step_5', 'vn-kho-03', 5, 'Châm thêm 50ml nước sôi, hạ nhỏ lửa đậy vung kho 15 phút đến khi nước kho sền sệt bám đều thịt gà.', NULL, 15),
('vn-kho-04_step_1', 'vn-kho-04', 1, 'Sườn non chặt miếng 3-4cm, luộc sơ qua nước sôi rồi ướp chút hạt nêm và nước mắm 10 phút.', NULL, NULL),
('vn-kho-04_step_2', 'vn-kho-04', 2, 'Cho dầu vào chảo rán sườn lửa vừa đến khi bề mặt xém vàng giòn hai mặt rồi vớt ra ráo dầu.', NULL, 8),
('vn-kho-04_step_3', 'vn-kho-04', 3, 'Pha nước sốt: 2 thìa nước mắm, 2 thìa giấm gạo, 2 thìa đường, 1 thìa tương cà khuấy tan.', NULL, NULL),
('vn-kho-04_step_4', 'vn-kho-04', 4, 'Phi thơm tỏi băm, xào nhuyễn cà chua và hành tây rồi đổ nước sốt pha sẵn vào đun sôi.', NULL, NULL),
('vn-kho-04_step_5', 'vn-kho-04', 5, 'Trút sườn đã rán vào đảo đều cho sốt quánh lại, ngấm đều phủ bóng khắp các miếng sườn.', NULL, 5),
('vn-kho-05_step_1', 'vn-kho-05', 1, 'Tôm rửa sạch, cắt bỏ râu và đuôi nhọn, để ráo nước hoàn toàn.', NULL, NULL),
('vn-kho-05_step_2', 'vn-kho-05', 2, 'Đặt chảo lên bếp, cho 1 thìa đường vào thắng nước màu cánh gián, phi thơm tỏi băm.', NULL, NULL),
('vn-kho-05_step_3', 'vn-kho-05', 3, 'Bật lửa lớn, trút tôm vào đảo nhanh tay đến khi tôm cong lại và chuyển màu đỏ cam tươi rói.', NULL, 3),
('vn-kho-05_step_4', 'vn-kho-05', 4, 'Nêm nước mắm và chút đường, rim nhỏ lửa đến khi nước sốt keo lại bám đều quanh vỏ tôm.', NULL, 5),
('vn-kho-05_step_5', 'vn-kho-05', 5, 'Rắc hành lá thái nhỏ và tiêu hạt giã dập, tắt bếp trút ra đĩa.', NULL, NULL),
('vn-kho-06_step_1', 'vn-kho-06', 1, 'Thịt ba chỉ thái miếng con chì vừa ăn, ướp với nước mắm, hành tím băm, tiêu xay 15 phút.', NULL, NULL),
('vn-kho-06_step_2', 'vn-kho-06', 2, 'Củ cải trắng gọt vỏ, cắt khúc dày 2cm, xóc chút muối hột 5 phút rồi rửa sạch để giảm vị hăng.', NULL, NULL),
('vn-kho-06_step_3', 'vn-kho-06', 3, 'Xào săn thịt ba chỉ cho ra bớt mỡ và thịt hơi xém cạnh vàng ươm.', NULL, NULL),
('vn-kho-06_step_4', 'vn-kho-06', 4, 'Cho củ cải vào đảo cùng 2 phút, thêm nước sôi xâm xấp mặt thịt, kho lửa nhỏ trong 20 phút.', NULL, 20),
('vn-kho-06_step_5', 'vn-kho-06', 5, 'Khi củ cải trong mềm và nước kho sánh sệt thì tắt bếp, rắc hành lá cắt khúc lên mặt.', NULL, NULL),
('vn-xao-01_step_1', 'vn-xao-01', 1, 'Rau muống nhặt bỏ lá già và gốc cứng, ngâm nước muối loãng rồi rửa sạch vớt ra rổ thưa.', NULL, NULL),
('vn-xao-01_step_2', 'vn-xao-01', 2, 'Đun một nồi nước thật sôi với chút muối, chần nhanh rau trong 30 giây rồi vớt thả ngay vào âu nước đá lạnh.', 'Sốc nhiệt nước đá giúp rau giữ màu xanh lục bảo và độ giòn sần sật.', NULL),
('vn-xao-01_step_3', 'vn-xao-01', 3, 'Đặt chảo sâu lòng lên bếp lửa lớn, cho dầu ăn vào phi thơm 2/3 lượng tỏi đập dập đến khi vàng ruộm.', NULL, NULL),
('vn-xao-01_step_4', 'vn-xao-01', 4, 'Thả rau muống vào xào đảo nhanh tay trên lửa cực lớn trong 1.5 phút cùng nước mắm.', NULL, 2),
('vn-xao-01_step_5', 'vn-xao-01', 5, 'Cho nốt phần tỏi tươi còn lại vào đảo đều thêm 10 giây rồi trút ngay ra đĩa.', NULL, NULL),
('vn-xao-02_step_1', 'vn-xao-02', 1, 'Thịt bò thái mỏng ngang thớ, ướp với tỏi băm, xì dầu, tiêu và 1 thìa dầu ăn để thịt không bị khô dai.', NULL, NULL),
('vn-xao-02_step_2', 'vn-xao-02', 2, 'Làm nóng chảo với lửa lớn, phi thơm tỏi rồi cho thịt bò vào đảo nhanh tay 1 phút đến khi tái thì trút ra đĩa riêng.', NULL, 1),
('vn-xao-02_step_3', 'vn-xao-02', 3, 'Vẫn chiếc chảo đó, thêm chút dầu xào hành tây và cà chua trong 2 phút cho vừa chín tới.', NULL, NULL),
('vn-xao-02_step_4', 'vn-xao-02', 4, 'Trút đĩa thịt bò trở lại chảo, đảo đều tay cùng rau củ trên lửa lớn trong 30 giây.', NULL, NULL),
('vn-xao-02_step_5', 'vn-xao-02', 5, 'Rắc hạt tiêu cay nồng, bày ra đĩa ăn nóng với cơm.', NULL, NULL),
('vn-xao-03_step_1', 'vn-xao-03', 1, 'Mực làm sạch nang mực, khứa vảy rồng trên thân rồi cắt miếng vuông, chần nhanh qua nước sôi có rượu gừng khử tanh.', NULL, NULL),
('vn-xao-03_step_2', 'vn-xao-03', 2, 'Phi thơm tỏi gừng băm, cho mực vào xào lửa lớn trong 1.5 phút cho mực săn giòn nở hoa rồi múc ra đĩa.', NULL, 2),
('vn-xao-03_step_3', 'vn-xao-03', 3, 'Xào dứa, cà chua và hành tây với lửa vừa cho tiết nước chua ngọt tự nhiên.', NULL, NULL),
('vn-xao-03_step_4', 'vn-xao-03', 4, 'Trút mực vào đảo đều cùng rau củ, nêm nước mắm và tiêu xay vừa khẩu vị.', NULL, NULL),
('vn-xao-03_step_5', 'vn-xao-03', 5, 'Rắc cần tây cắt khúc đảo nhanh 15 giây rồi tắt bếp.', NULL, NULL),
('vn-xao-04_step_1', 'vn-xao-04', 1, 'Thịt bò ướp với tỏi băm, 1 thìa dầu hào, tiêu và chút dầu ăn trong 10 phút.', NULL, NULL),
('vn-xao-04_step_2', 'vn-xao-04', 2, 'Bông cải và cà rốt chần sơ qua nước sôi 1 phút để giữ màu tươi và độ giòn ngọt.', NULL, NULL),
('vn-xao-04_step_3', 'vn-xao-04', 3, 'Phi tỏi thơm trên chảo nóng, cho thịt bò vào xào chín tái trong 1 phút rồi gắp riêng ra.', NULL, NULL),
('vn-xao-04_step_4', 'vn-xao-04', 4, 'Cho bông cải xanh và cà rốt vào xào nhanh với 1 thìa dầu hào và 2 thìa nước lọc trong 2 phút.', NULL, NULL),
('vn-xao-04_step_5', 'vn-xao-04', 5, 'Đổ thịt bò vào đảo chung 30 giây cho hòa quyện hương vị, rắc tiêu và múc ra đĩa.', NULL, NULL),
('vn-xao-05_step_1', 'vn-xao-05', 1, 'Su su gọt vỏ rửa sạch mủ, bào thành sợi dài.', NULL, NULL),
('vn-xao-05_step_2', 'vn-xao-05', 2, 'Đánh tan 2 quả trứng gà cùng 1 thìa cà phê nước mắm và chút tiêu.', NULL, NULL),
('vn-xao-05_step_3', 'vn-xao-05', 3, 'Phi thơm hành tím với dầu ăn, cho su su vào xào lửa lớn trong 3 phút cho chín tới.', NULL, NULL),
('vn-xao-05_step_4', 'vn-xao-05', 4, 'Rưới trứng gà đánh tan đều khắp chảo su su, để 15 giây cho trứng se lại rồi dùng đũa đảo nhẹ tay.', NULL, NULL),
('vn-xao-05_step_5', 'vn-xao-05', 5, 'Rắc hành hoa và tiêu xay, tắt bếp thưởng thức nóng.', NULL, NULL),
('vn-xao-06_step_1', 'vn-xao-06', 1, 'Đậu cô ve tước xơ 2 bên sườn, cắt vát chéo, rửa sạch.', NULL, NULL),
('vn-xao-06_step_2', 'vn-xao-06', 2, 'Thịt bò thái mỏng ướp tỏi băm, hạt tiêu và dầu ăn.', NULL, NULL),
('vn-xao-06_step_3', 'vn-xao-06', 3, 'Xào nhanh thịt bò trên lửa lớn trong 1 phút rồi múc ra đĩa.', NULL, NULL),
('vn-xao-06_step_4', 'vn-xao-06', 4, 'Phi thêm tỏi, cho đậu cô ve vào xào với lửa lớn, thêm chút xíu nước để đậu chín giòn đều trong 3 phút.', NULL, NULL),
('vn-xao-06_step_5', 'vn-xao-06', 5, 'Đổ thịt bò vào đảo lại 30 giây, nêm nếm gia vị và rắc tiêu thơm.', NULL, NULL),
('vn-chien-01_step_1', 'vn-chien-01', 1, 'Đậu phụ cắt miếng vuông vừa ăn, thấm khô nước bằng khăn giấy sạch.', NULL, NULL),
('vn-chien-01_step_2', 'vn-chien-01', 2, 'Đun nóng chảo dầu, chiên lướt ván đậu phụ đến khi vỏ ngoài vàng giòn rụm nhưng bên trong vẫn mềm béo.', NULL, 6),
('vn-chien-01_step_3', 'vn-chien-01', 3, 'Phi thơm đầu hành trắng, cho cà chua thái hạt lựu vào xào nhuyễn cùng nước mắm và chút nước.', NULL, NULL),
('vn-chien-01_step_4', 'vn-chien-01', 4, 'Thả đậu phụ vào đảo nhẹ tay cho lớp sốt cà chua ngấm đều quanh từng miếng đậu trong 3 phút.', NULL, NULL),
('vn-chien-01_step_5', 'vn-chien-01', 5, 'Rắc hành lá thái nhỏ và tiêu thơm, múc ra đĩa ăn kèm cơm nóng hổi.', NULL, NULL),
('vn-chien-02_step_1', 'vn-chien-02', 1, 'Xào sơ thịt bằm và nấm băm cùng hành khô cho chín tới và ráo bớt nước.', NULL, NULL),
('vn-chien-02_step_2', 'vn-chien-02', 2, 'Đập 4 quả trứng gà vào tô, nêm nước mắm, tiêu và hành hoa rồi đánh bông nhẹ.', NULL, NULL),
('vn-chien-02_step_3', 'vn-chien-02', 3, 'Trộn đều phần thịt bằm nấm đã xào vào âu trứng.', NULL, NULL),
('vn-chien-02_step_4', 'vn-chien-02', 4, 'Đun nóng dầu trong chảo, đổ trứng vào dàn đều, đậy vung chiên lửa nhỏ 4 phút cho chín phồng đáy.', NULL, 4),
('vn-chien-02_step_5', 'vn-chien-02', 5, 'Khéo léo lật mặt trứng chiên thêm 2 phút cho vàng đều hai mặt rồi cắt miếng tam giác.', NULL, NULL),
('vn-chien-03_step_1', 'vn-chien-03', 1, 'Cánh gà rửa sạch với nước muối gừng, khía nhẹ 2 đường ở mặt trong để nhanh chín và ngấm vị.', NULL, NULL),
('vn-chien-03_step_2', 'vn-chien-03', 2, 'Chiên cánh gà ngập dầu với lửa vừa đến khi da gà giòn rụm và ngả màu vàng cánh gián thì vớt ra thấm dầu.', NULL, 12),
('vn-chien-03_step_3', 'vn-chien-03', 3, 'Pha sốt nước mắm: 2 thìa mắm, 2 thìa đường, 1 thìa nước lọc, chút tiêu khuấy tan.', NULL, NULL),
('vn-chien-03_step_4', 'vn-chien-03', 4, 'Phi thơm tỏi và ớt băm trên chảo với 1 thìa dầu, đổ sốt nước mắm vào đun sôi sủi bọt keo lại.', NULL, NULL),
('vn-chien-03_step_5', 'vn-chien-03', 5, 'Trút cánh gà chiên vào đảo nhanh tay 1 phút để sốt mắm óng ánh phủ đều quanh cánh gà.', NULL, NULL),
('vn-chien-04_step_1', 'vn-chien-04', 1, 'Thịt cá thấm khô, xay nhuyễn rồi dùng thìa quết mạnh tay liên tục 10 phút để chả đạt độ dai giòn tự nhiên.', NULL, NULL),
('vn-chien-04_step_2', 'vn-chien-04', 2, 'Trộn mỡ heo hạt lựu, thì là thái nhỏ, hành tím, nước mắm, tiêu sọ đập dập vào khối chả cá.', NULL, NULL),
('vn-chien-04_step_3', 'vn-chien-04', 3, 'Thoa chút dầu ăn lên lòng bàn tay, nặn chả cá thành từng miếng tròn dẹt vừa ăn.', NULL, NULL),
('vn-chien-04_step_4', 'vn-chien-04', 4, 'Đun nóng dầu, thả từng miếng chả cá vào chiên lửa vừa cho phồng xốp vàng ruộm hai mặt.', NULL, 8),
('vn-chien-04_step_5', 'vn-chien-04', 5, 'Gắp chả cá ra đĩa lót giấy thấm dầu, ăn nóng chấm tương ớt hoặc nước mắm gừng thì là.', NULL, NULL),
('vn-chien-05_step_1', 'vn-chien-05', 1, 'Trộn đều thịt xay, tôm, mộc nhĩ, nấm hương, cà rốt, miến dong cắt khúc, hành hoa và lòng đỏ trứng gà.', NULL, NULL),
('vn-chien-05_step_2', 'vn-chien-05', 2, 'Trải bánh đa nem ra đĩa phẳng, cho lượng nhân vừa phải vào cuốn tròn vừa tay không quá chặt kẻo bục nem.', NULL, NULL),
('vn-chien-05_step_3', 'vn-chien-05', 3, 'Chiên nem 2 lần lửa: Lần 1 chiên chín tới ở lửa nhỏ vừa rồi vớt ra để nguội.', NULL, 10),
('vn-chien-05_step_4', 'vn-chien-05', 4, 'Lần 2: Trước khi ăn chiên lại trên lửa lớn 2 phút để vỏ nem giòn rụm lâu và không bị ngậm dầu.', NULL, 3),
('vn-chien-05_step_5', 'vn-chien-05', 5, 'Bày ra đĩa cùng rau sống kinh giới tía tô, chấm nước mắm pha chua ngọt tỏi ớt cà rốt đu đủ muối.', NULL, NULL),
('vn-chien-06_step_1', 'vn-chien-06', 1, 'Cá rô phi làm sạch màng đen trong bụng, khía vát sâu lên thân, lau thật khô ráo cả trong lẫn ngoài.', NULL, NULL),
('vn-chien-06_step_2', 'vn-chien-06', 2, 'Đun dầu ăn sôi già, thả cá vào chiên vàng giòn một mặt rồi mới nhẹ nhàng lật sang mặt còn lại.', NULL, 15),
('vn-chien-06_step_3', 'vn-chien-06', 3, 'Pha nước mắm chấm: 2 thìa nước mắm, 1 thìa đường, gừng giã nhuyễn, tỏi ớt băm và nước cốt chanh khuấy đều.', NULL, NULL),
('vn-chien-06_step_4', 'vn-chien-06', 4, 'Cá chín vàng giòn rụm cả 2 mặt thì vớt ra gác lên rây cho ráo dầu.', NULL, NULL),
('vn-chien-06_step_5', 'vn-chien-06', 5, 'Thưởng thức khi cá còn nóng hổi giòn rụm cùng cơm và rau luộc.', NULL, NULL),
('vn-hap-01_step_1', 'vn-hap-01', 1, 'Gà làm sạch xát muối và gừng đập dập quanh da để khử sạch mùi hôi, rửa lại để ráo.', NULL, NULL),
('vn-hap-01_step_2', 'vn-hap-01', 2, 'Xếp một lớp sả đập dập và gừng thái lát dưới đáy xửng hấp, đặt gà lên trên.', NULL, NULL),
('vn-hap-01_step_3', 'vn-hap-01', 3, 'Đậy kín nắp xửng hấp cách thủy trên lửa vừa trong 25 phút đến khi dùng tăm chọc không còn ứa nước hồng.', NULL, 25),
('vn-hap-01_step_4', 'vn-hap-01', 4, 'Gà chín vớt ra ngâm ngay vào âu nước đá lạnh 3 phút rồi vớt ra để da gà se giòn căng mọng.', NULL, NULL),
('vn-hap-01_step_5', 'vn-hap-01', 5, 'Chặt gà thành từng miếng vuông đẹp mắt, rắc nhiều lá chanh thái chỉ lên trên, chấm muối tiêu chanh ớt.', NULL, NULL),
('vn-hap-02_step_1', 'vn-hap-02', 1, 'Thịt ba chỉ rửa sạch, dùng dây dù buộc nhẹ cuộn tròn để miếng thịt luộc thái ra tròn đẹp.', NULL, NULL),
('vn-hap-02_step_2', 'vn-hap-02', 2, 'Đun nồi nước sôi lăn tăn cùng củ hành tím và gừng đập dập, thả miếng thịt vào luộc lửa vừa.', NULL, 15),
('vn-hap-02_step_3', 'vn-hap-02', 3, 'Vớt thịt ngâm ngay vào thau nước đá lạnh có vắt chút nước cốt chanh để thịt trắng phau và bì giòn.', 'Ngâm nước đá sau luộc giúp giữ độ mọng nước và không bị thâm bì.', NULL),
('vn-hap-02_step_4', 'vn-hap-02', 4, 'Thịt nguội hẳn dùng dao thật sắc thái lát mỏng tang xếp đều ra đĩa.', NULL, NULL),
('vn-hap-02_step_5', 'vn-hap-02', 5, 'Pha mắm chấm chanh tỏi ớt đánh bông bọt trắng, ăn kèm rau húng quế và dưa chuột.', NULL, NULL),
('vn-hap-03_step_1', 'vn-hap-03', 1, 'Cá mổ sạch vẩy và mang, khía 3 đường chéo trên thân, ướp chút hạt nêm và gừng sợi trong bụng cá.', NULL, NULL),
('vn-hap-03_step_2', 'vn-hap-03', 2, 'Đặt cá vào đĩa sâu lòng, rải một nửa gừng sợi lên trên rồi cho vào xửng hấp chín tới trong 18 phút.', NULL, 18),
('vn-hap-03_step_3', 'vn-hap-03', 3, 'Pha sốt xì dầu: 3 thìa xì dầu, 1 thìa dầu hào, 1 thìa đường và 2 thìa nước lọc đun sôi lăn tăn.', NULL, NULL),
('vn-hap-03_step_4', 'vn-hap-03', 4, 'Rải hành hoa chẻ sợi và gừng tươi còn lại lên khắp mình cá, đun dầu ăn thật sôi rồi xối trực tiếp lên hành gừng để dậy mùi thơm nức.', NULL, NULL),
('vn-hap-03_step_5', 'vn-hap-03', 5, 'Rưới nước sốt xì dầu quanh thân cá, dọn lên bàn ăn nóng kèm bánh tráng cuốn rau sống.', NULL, NULL),
('vn-hap-04_step_1', 'vn-hap-04', 1, 'Thịt ba chỉ thái hạt lựu đảo trên chảo nhỏ lấy tóp mỡ vàng giòn, vớt tóp ra riêng.', NULL, NULL),
('vn-hap-04_step_2', 'vn-hap-04', 2, 'Dùng mỡ đó phi thơm hành tỏi băm, cho tôm khô vào xào thơm.', NULL, NULL),
('vn-hap-04_step_3', 'vn-hap-04', 3, 'Pha 3 thìa nước mắm ngon và 2 thìa đường vào chảo, đun nhỏ lửa đến khi mắm keo sền sệt thì thả tóp mỡ, ớt hiểm và tiêu sọ vào.', NULL, 8),
('vn-hap-04_step_4', 'vn-hap-04', 4, 'Đun sôi nồi nước với chút muối, lần lượt luộc chín tới cà rốt, su su và bông cải xanh rồi vớt ra đĩa.', NULL, NULL),
('vn-hap-04_step_5', 'vn-hap-04', 5, 'Bày mẹt rau củ xanh mướt quanh niêu kho quẹt bốc khói nghi ngút.', NULL, NULL),
('vn-hap-05_step_1', 'vn-hap-05', 1, 'Mực rút túi mực và xương sống mềm, rửa sạch để ráo.', NULL, NULL),
('vn-hap-05_step_2', 'vn-hap-05', 2, 'Lót sả cây đập dập dưới đáy đĩa hấp, xếp mực lên trên, rải gừng non và ớt sừng khắp thân mực.', NULL, NULL),
('vn-hap-05_step_3', 'vn-hap-05', 3, 'Đặt vào xửng nước sôi hấp cách thủy với lửa lớn trong đúng 8 phút để mực chín giòn ngọt không bị dai.', NULL, 8),
('vn-hap-05_step_4', 'vn-hap-05', 4, 'Cắt mực thành từng khoanh tròn vừa ăn xếp lại ngay ngắn trên đĩa.', NULL, NULL),
('vn-hap-05_step_5', 'vn-hap-05', 5, 'Chấm cùng muối ớt tiêu chanh hoặc mù tạt xì dầu đậm vị.', NULL, NULL),
('vn-hap-06_step_1', 'vn-hap-06', 1, 'Tôm cắt bớt râu và chân bơi, rửa sạch để ráo.', NULL, NULL),
('vn-hap-06_step_2', 'vn-hap-06', 2, 'Đổ 1 bát nước dừa tươi vào nồi cùng sả đập dập, đun sôi bùng lên.', NULL, NULL),
('vn-hap-06_step_3', 'vn-hap-06', 3, 'Thả tôm vào đảo đều và đậy nắp hấp trong 6 phút đến khi tôm cong đều chuyển màu đỏ rực.', NULL, 6),
('vn-hap-06_step_4', 'vn-hap-06', 4, 'Gắp tôm ra đĩa sâu lòng, xếp quanh quả dừa tươi hoặc trang trí cùng hành hoa.', NULL, NULL),
('vn-hap-06_step_5', 'vn-hap-06', 5, 'Thưởng thức nóng chấm muối tiêu chanh ớt ngọt lịm từng thớ thịt.', NULL, NULL),
('vn-cuon-01_step_1', 'vn-cuon-01', 1, 'Tôm luộc chín bóc vỏ chẻ đôi sống lưng. Thịt ba chỉ luộc chín tới thái lát mỏng vừa.', NULL, NULL),
('vn-cuon-01_step_2', 'vn-cuon-01', 2, 'Thấm ướt nhẹ bánh tráng dẻo, đặt xà lách, rau thơm và một lọn bún tươi lên bánh.', NULL, NULL),
('vn-cuon-01_step_3', 'vn-cuon-01', 3, 'Xếp thịt ba chỉ vào trong, gấp mép bánh 2 bên lại rồi đặt 2-3 nửa con tôm mặt đỏ hướng ra ngoài cùng nhánh hẹ dài ló ra.', NULL, NULL),
('vn-cuon-01_step_4', 'vn-cuon-01', 4, 'Cuộn tròn chặt tay để thấy rõ lớp tôm thịt đẹp mắt qua lớp bánh tráng trong veo.', NULL, NULL),
('vn-cuon-01_step_5', 'vn-cuon-01', 5, 'Pha sốt chấm: Xào tỏi với tương đen bơ đậu phộng cho sánh mịn, rắc đậu phộng rang giã dập và ớt băm.', NULL, NULL),
('vn-cuon-02_step_1', 'vn-cuon-02', 1, 'Thịt bò ướp tỏi băm, tiêu xay và nước mắm 10 phút.', NULL, NULL),
('vn-cuon-02_step_2', 'vn-cuon-02', 2, 'Xào thịt bò trên chảo lửa cực lớn trong 1 phút cho thịt chín tới mềm mọng, không bị ra nước.', NULL, NULL),
('vn-cuon-02_step_3', 'vn-cuon-02', 3, 'Trải từng lá bánh phở vuông ra đĩa, đặt xà lách, rau thơm kinh giới và thịt bò xào lên trên.', NULL, NULL),
('vn-cuon-02_step_4', 'vn-cuon-02', 4, 'Cuộn tròn đều tay thành từng cuốn phở thon dài trắng ngần.', NULL, NULL),
('vn-cuon-02_step_5', 'vn-cuon-02', 5, 'Bày ra đĩa, chấm cùng nước mắm chua ngọt pha tỏi ớt cà rốt đu đủ giòn.', NULL, NULL),
('vn-cuon-03_step_1', 'vn-cuon-03', 1, 'Tai heo luộc cùng chút dấm gừng trong 15 phút, vớt ngâm nước đá rồi thái lát thật mỏng.', NULL, 15),
('vn-cuon-03_step_2', 'vn-cuon-03', 2, 'Hoa chuối bào mỏng ngâm vào nước pha chanh muối loãng 15 phút để không bị thâm đen, vớt vắt ráo nước.', NULL, NULL),
('vn-cuon-03_step_3', 'vn-cuon-03', 3, 'Pha nước trộn nộm: 3 thìa nước mắm, 3 thìa đường, 3 thìa nước cốt chanh, tỏi ớt băm khuấy tan.', NULL, NULL),
('vn-cuon-03_step_4', 'vn-cuon-03', 4, 'Cho hoa chuối, tai heo, cà rốt, giá đỗ và rau răm vào âu lớn, rưới nước sốt trộn đều tay.', NULL, NULL),
('vn-cuon-03_step_5', 'vn-cuon-03', 5, 'Để 5 phút cho ngấm, chắt bớt nước nộm, rắc lạc rang giã dập lên trên trước khi dọn đĩa.', NULL, NULL),
('vn-cuon-04_step_1', 'vn-cuon-04', 1, 'Thịt gà luộc xé miếng dài vừa ăn. Bắp cải rửa sạch bào thật mỏng để ráo nước.', NULL, NULL),
('vn-cuon-04_step_2', 'vn-cuon-04', 2, 'Hành tây thái mỏng ngâm nước đá có pha chút giấm 10 phút để hết hăng và giữ độ giòn tan.', NULL, NULL),
('vn-cuon-04_step_3', 'vn-cuon-04', 3, 'Pha sốt trộn: 2 thìa mắm ngon, 2 thìa đường, 2 thìa cốt chanh, ớt băm và chút tiêu xay.', NULL, NULL),
('vn-cuon-04_step_4', 'vn-cuon-04', 4, 'Trộn đều thịt gà xé, bắp cải, hành tây cùng nước sốt trong âu lớn khoảng 3 phút.', NULL, NULL),
('vn-cuon-04_step_5', 'vn-cuon-04', 5, 'Thêm rau răm thái nhỏ và hành phi giòn, bày ra đĩa ăn kèm phồng tôm giòn rụm.', NULL, NULL),
('vn-cuon-05_step_1', 'vn-cuon-05', 1, 'Đu đủ xanh và cà rốt nạo sợi dài, ngâm nước muối loãng 10 phút rồi vắt ráo để sợi nộm giòn tan.', NULL, NULL),
('vn-cuon-05_step_2', 'vn-cuon-05', 2, 'Pha nước trộn nộm chua ngọt chuẩn vị phố cổ: Giấm gạo thơm, đường cát, nước mắm và ớt tươi băm.', NULL, NULL),
('vn-cuon-05_step_3', 'vn-cuon-05', 3, 'Bốc một nắm sợi đu đủ cà rốt đặt vào đĩa sâu lòng.', NULL, NULL),
('vn-cuon-05_step_4', 'vn-cuon-05', 4, 'Rải bò khô xé sợi, rau kinh giới, rau húng thái khúc và lạc rang giã vỡ lên trên.', NULL, NULL),
('vn-cuon-05_step_5', 'vn-cuon-05', 5, 'Rưới đều nước giấm mắm chua ngọt trước khi thưởng thức, trộn đều tay và cảm nhận vị giòn sần sật.', NULL, NULL),
('vn-cuon-06_step_1', 'vn-cuon-06', 1, 'Trộn giò sống và thịt xay cùng hành tỏi băm, nước mắm, mật ong, tiêu sọ, quết đều tay 10 phút cho dẻo quánh.', NULL, NULL),
('vn-cuon-06_step_2', 'vn-cuon-06', 2, 'Cây sả bóc bớt vỏ già, thoa dầu ăn lên tay lấy lượng thịt vừa đủ bọc quanh đầu cây sả.', NULL, NULL),
('vn-cuon-06_step_3', 'vn-cuon-06', 3, 'Nướng nem trên than hoa hoặc nồi chiên không dầu ở 180°C trong 15 phút, trở mặt cho vàng đều xém cạnh.', NULL, 15),
('vn-cuon-06_step_4', 'vn-cuon-06', 4, 'Pha nước lèo chấm Huế: Gan heo băm nhỏ xào với tương đậu phộng và mè rang sánh đặc.', NULL, NULL),
('vn-cuon-06_step_5', 'vn-cuon-06', 5, 'Dùng bánh tráng cuốn nem lụi cùng rau sống, chuối chát, dưa leo chấm ngập nước lèo bùi béo.', NULL, NULL),
('vn-bun-01_step_1', 'vn-bun-01', 1, 'Nước dùng ninh xương ống bò cùng gừng nướng, hành củ nướng, hồi quế trong nhiều giờ, vớt bọt liên tục để nước trong veo.', NULL, NULL),
('vn-bun-01_step_2', 'vn-bun-01', 2, 'Thịt bò thái mỏng ngang thớ, ướp với tỏi băm, gừng và chút xíu nước mắm tiêu.', NULL, NULL),
('vn-bun-01_step_3', 'vn-bun-01', 3, 'Làm nóng chảo với lửa lớn, cho thịt bò vào xào tái lăn nhanh trong 45 giây cho dậy mùi thơm xém cạnh.', NULL, 1),
('vn-bun-01_step_4', 'vn-bun-01', 4, 'Chần bánh phở qua nước sôi xếp vào tô, đặt thịt bò xào tái lăn lên trên cùng đầu hành hoa chẻ.', NULL, NULL),
('vn-bun-01_step_5', 'vn-bun-01', 5, 'Chan nước dùng đang sôi sùng sục ngập bánh phở, rắc hành ngò thái nhỏ và vắt chanh ớt thưởng thức.', NULL, NULL),
('vn-bun-02_step_1', 'vn-bun-02', 1, 'Ướp chả miếng và chả viên với nước mắm, mật ong, nước hàng, hành tỏi băm và tiêu xay 20 phút.', NULL, NULL),
('vn-bun-02_step_2', 'vn-bun-02', 2, 'Viên chả băm thành từng miếng tròn dẹt, kẹp vỉ nướng than hoa cùng chả miếng đến khi mỡ xèo xèo vàng xém thơm nức.', NULL, 15),
('vn-bun-02_step_3', 'vn-bun-02', 3, 'Làm dưa góp: Cà rốt và đu đủ thái lát mỏng ngâm giấm đường muối giòn tan.', NULL, NULL),
('vn-bun-02_step_4', 'vn-bun-02', 4, 'Pha nước chấm bún chả: Nước sôi ấm, nước mắm, giấm thanh, đường theo tỉ lệ 5:1:1:1 ấm nóng.', NULL, NULL),
('vn-bun-02_step_5', 'vn-bun-02', 5, 'Thả chả nướng nóng hổi và dưa góp vào bát nước mắm, ăn kèm bún tươi và đĩa rau sống tía tô kinh giới.', NULL, NULL),
('vn-bun-03_step_1', 'vn-bun-03', 1, 'Ninh xương heo và bắp bò cùng bó sả đập dập, hớt bọt kỹ để nước dùng trong ngọt đậm.', NULL, 30),
('vn-bun-03_step_2', 'vn-bun-03', 2, 'Mắm ruốc Huế khuấy tan với nước lạnh để lắng cặn, chắt lấy nước trong trút vào nồi nước dùng.', NULL, NULL),
('vn-bun-03_step_3', 'vn-bun-03', 3, 'Phi thơm dầu màu điều với sả băm, tỏi băm và ớt bột cho vào nồi để tạo màu đỏ cam hấp dẫn.', NULL, NULL),
('vn-bun-03_step_4', 'vn-bun-03', 4, 'Chần bún sợi to vào tô, xếp bắp bò thái mỏng, khoanh giò heo và chả lụa lên trên.', NULL, NULL),
('vn-bun-03_step_5', 'vn-bun-03', 5, 'Chan nước dùng đang sôi lăn tăn, rắc hành tây thái mỏng, hoa chuối bào sợi và vắt chanh thưởng thức.', NULL, NULL),
('vn-bun-04_step_1', 'vn-bun-04', 1, 'Đun nước lọc cua với chút muối trên lửa vừa, hạ nhỏ lửa khi sôi để mảng riêu cua kết tảng nổi lên bề mặt.', NULL, NULL),
('vn-bun-04_step_2', 'vn-bun-04', 2, 'Vớt mảng riêu cua ra bát riêng để không bị nát vỡ.', NULL, NULL),
('vn-bun-04_step_3', 'vn-bun-04', 3, 'Xào cà chua với chút dầu màu điều rồi trút vào nồi nước cua, thêm giấm bỗng nếp chua thanh tao.', NULL, 5),
('vn-bun-04_step_4', 'vn-bun-04', 4, 'Cho đậu rán vàng vào nồi nước dùng đun sôi nhỏ lửa cho ngấm vị.', NULL, NULL),
('vn-bun-04_step_5', 'vn-bun-04', 5, 'Cho bún vào tô, thêm riêu cua, thịt bò chần tái, đậu rán, chan nước dùng cà chua nóng hổi rắc hành hoa lên trên.', NULL, NULL),
('vn-bun-05_step_1', 'vn-bun-05', 1, 'Thịt thái lát mỏng ướp sả băm, tỏi băm, nước mắm, mật ong, dầu hào và mè trắng 30 phút.', NULL, NULL),
('vn-bun-05_step_2', 'vn-bun-05', 2, 'Nướng thịt trên than hoa hoặc lò nướng 200°C trong 12 phút đến khi thịt vàng óng xém cạnh.', NULL, 12),
('vn-bun-05_step_3', 'vn-bun-05', 3, 'Hành lá thái nhỏ cho vào chén với chút muối, xối dầu ăn đun thật sôi vào làm mỡ hành xanh ngắt.', NULL, NULL),
('vn-bun-05_step_4', 'vn-bun-05', 4, 'Xếp rau sống, dưa leo băm và bún tươi vào tô lớn, gắp thịt nướng nóng hổi lên trên.', NULL, NULL),
('vn-bun-05_step_5', 'vn-bun-05', 5, 'Rưới mỡ hành, đồ chua và rắc đậu phộng rang, chan nước mắm chua ngọt trộn đều thưởng thức.', NULL, NULL),
('vn-bun-06_step_1', 'vn-bun-06', 1, 'Miến dong ngâm nước ấm 10 phút cho mềm rồi cắt khúc vừa ăn.', NULL, NULL),
('vn-bun-06_step_2', 'vn-bun-06', 2, 'Nấm hương ngâm nở rửa sạch, xào sơ với chút nước mắm và đầu hành phi cho thơm ngậy.', NULL, NULL),
('vn-bun-06_step_3', 'vn-bun-06', 3, 'Đun sôi nước luộc gà, trút nấm hương vào nấu trong 5 phút để nước dùng thơm mùi nấm.', NULL, 5),
('vn-bun-06_step_4', 'vn-bun-06', 4, 'Chần miến vào nồi nước dùng 1 phút rồi vớt ra tô, xếp thịt gà xé phay lên trên.', NULL, NULL),
('vn-bun-06_step_5', 'vn-bun-06', 5, 'Chan nước dùng gà nóng hổi ngập miến, rắc hành hoa rau răm và hạt tiêu cay thơm.', NULL, NULL),
('vn-chay-01_step_1', 'vn-chay-01', 1, 'Đậu phụ cắt vuông chiên vàng giòn các mặt. Nấm đông cô ngâm nở cắt chân khía chữ thập trên mũ.', NULL, NULL),
('vn-chay-01_step_2', 'vn-chay-01', 2, 'Phi thơm boa-rô trên chảo, cho nấm vào xào sơ cho săn thơm.', NULL, NULL),
('vn-chay-01_step_3', 'vn-chay-01', 3, 'Pha sốt kho: 3 thìa nước tương, 1 thìa dầu hào chay, 1 thìa đường và nửa chén nước lọc.', NULL, NULL),
('vn-chay-01_step_4', 'vn-chay-01', 4, 'Xếp đậu phụ và nấm vào nồi đất, đổ nước sốt kho lửa nhỏ trong 12 phút đến khi nước keo sánh.', NULL, 12),
('vn-chay-01_step_5', 'vn-chay-01', 5, 'Rưới 1 thìa dầu mè thơm và rắc nhiều tiêu đen xay lên trên, dùng nóng với cơm trắng.', NULL, NULL),
('vn-chay-02_step_1', 'vn-chay-02', 1, 'Hạt sen thông tâm ngâm mềm. Cà rốt và củ quả gọt vỏ cắt miếng vừa ăn.', NULL, NULL),
('vn-chay-02_step_2', 'vn-chay-02', 2, 'Đun sôi 1 lít nước, cho hạt sen và bắp ngọt vào hầm nhỏ lửa 15 phút cho tiết vị ngọt thanh.', NULL, 15),
('vn-chay-02_step_3', 'vn-chay-02', 3, 'Cho cà rốt và các loại nấm tươi vào nấu thêm 5 phút cho nấm chín giòn ngọt.', NULL, 5),
('vn-chay-02_step_4', 'vn-chay-02', 4, 'Nêm chút muối hột và hạt nêm chay nấm cho vừa vị ngọt dịu thanh tao.', NULL, NULL),
('vn-chay-02_step_5', 'vn-chay-02', 5, 'Múc canh ra tô sứ, rắc ngò gai thái nhỏ lên trên và thưởng thức nóng.', NULL, NULL),
('vn-chay-03_step_1', 'vn-chay-03', 1, 'Mì chần qua nước sôi 1 phút rồi xả ngay nước lạnh, trộn chút dầu ăn để sợi mì tơi giòn.', NULL, NULL),
('vn-chay-03_step_2', 'vn-chay-03', 2, 'Phi thơm hành boa-rô, cho nấm đùi gà vào xào lửa lớn cho xém cạnh thơm nức.', NULL, NULL),
('vn-chay-03_step_3', 'vn-chay-03', 3, 'Cho cải ngọt và cà rốt vào đảo chung trong 2 phút với 1 thìa xì dầu.', NULL, NULL),
('vn-chay-03_step_4', 'vn-chay-03', 4, 'Trút sợi mì vào chảo, rưới sốt dầu hào chay đảo đều tay trên lửa lớn 2 phút.', NULL, 2),
('vn-chay-03_step_5', 'vn-chay-03', 5, 'Rắc hạt tiêu thơm lừng và trút ra đĩa thưởng thức ngay khi còn nóng.', NULL, NULL),
('vn-chay-04_step_1', 'vn-chay-04', 1, 'Cà tím để nguyên cuống rửa sạch, dùng nĩa xăm vài lỗ nhỏ trên thân quả.', NULL, NULL),
('vn-chay-04_step_2', 'vn-chay-04', 2, 'Nướng cà tím trên than hoa hoặc nồi chiên không dầu ở 190°C trong 15 phút đến khi vỏ cháy xém mềm nhũn.', NULL, 15),
('vn-chay-04_step_3', 'vn-chay-04', 3, 'Lột sạch lớp vỏ cháy bên ngoài, xếp phần thịt cà trắng mềm ra đĩa, dùng dĩa tước nhẹ thành dải dài.', NULL, NULL),
('vn-chay-04_step_4', 'vn-chay-04', 4, 'Hành hoa thái nhỏ xối dầu nóng làm mỡ hành xanh mướt, rải đều lên khắp thân cà tím.', NULL, NULL),
('vn-chay-04_step_5', 'vn-chay-04', 5, 'Rưới nước tương pha tỏi ớt đường chua ngọt, rắc thêm đậu phộng rang giã dập lên trên.', NULL, NULL),
('vn-chay-05_step_1', 'vn-chay-05', 1, 'Đậu hũ non cắt khoanh tròn dày 1.5cm, xếp ra đĩa sâu lòng đem hấp cách thủy 5 phút cho nóng ấm.', NULL, NULL),
('vn-chay-05_step_2', 'vn-chay-05', 2, 'Nấm rơm cạo sạch chân nấm ngâm nước muối 10 phút rồi vớt ráo.', NULL, NULL),
('vn-chay-05_step_3', 'vn-chay-05', 3, 'Phi thơm boa-rô, cho nấm rơm vào xào lửa lớn trong 2 phút.', NULL, NULL),
('vn-chay-05_step_4', 'vn-chay-05', 4, 'Hòa sốt gồm: 2 thìa dầu hào chay, 1 thìa xì dầu, 1 thìa bột bắp và 4 thìa nước đổ vào chảo đun sánh lại.', NULL, 3),
('vn-chay-05_step_5', 'vn-chay-05', 5, 'Rưới nước sốt nấm rơm đang sôi lục bục phủ đều lên đĩa đậu hũ non, rắc tiêu thơm và ngò rí.', NULL, NULL),
('vn-chay-06_step_1', 'vn-chay-06', 1, 'Cải xanh rửa sạch, cắt khúc 3cm để ráo. Đậu phụ cắt miếng vuông nhỏ.', NULL, NULL),
('vn-chay-06_step_2', 'vn-chay-06', 2, 'Đun sôi 800ml nước, thả gừng già đập dập vào đun sôi 2 phút cho dậy mùi cay thơm.', NULL, 2),
('vn-chay-06_step_3', 'vn-chay-06', 3, 'Thả đậu phụ vào nấu sôi lăn tăn, nêm muối và hạt nêm chay vừa miệng.', NULL, NULL),
('vn-chay-06_step_4', 'vn-chay-06', 4, 'Cho rau cải xanh vào ấn chìm xuống nước, đun sôi bùng lại trong 1.5 phút để rau vừa chín giữ màu xanh mướt.', NULL, NULL),
('vn-chay-06_step_5', 'vn-chay-06', 5, 'Múc canh ra tô ăn nóng, vị đắng nhẹ của cải hòa cùng gừng cay ấm áp.', NULL, NULL),
('vn-sang-01_step_1', 'vn-sang-01', 1, 'Đập 1 quả trứng gà vào tô cơm nguội, dùng bao tay bóp nhẹ để lòng đỏ trứng bao bọc đều từng hạt cơm.', NULL, NULL),
('vn-sang-01_step_2', 'vn-sang-01', 2, 'Đun nóng dầu ăn trên chảo lớn, cho tỏi băm vào phi vàng giòn thơm nức rồi vớt 1 nửa ra để riêng.', NULL, NULL),
('vn-sang-01_step_3', 'vn-sang-01', 3, 'Đập quả trứng còn lại vào chảo đảo tơi thành các vụn trứng vàng óng.', NULL, NULL),
('vn-sang-01_step_4', 'vn-sang-01', 4, 'Trút cơm vào chảo đảo liên tục trên lửa lớn trong 5 phút đến khi hạt cơm săn lại nhảy tanh tách.', NULL, 5),
('vn-sang-01_step_5', 'vn-sang-01', 5, 'Rưới nước mắm quanh thành chảo cho dậy mùi thơm khói, rắc hành lá và tỏi phi giòn lên trên.', NULL, NULL),
('vn-sang-02_step_1', 'vn-sang-02', 1, 'Làm nóng chảo, cho chút bơ vào đun chảy rồi đập trứng gà vào ốp la lòng đào trong 2 phút.', NULL, 2),
('vn-sang-02_step_2', 'vn-sang-02', 2, 'Rạch dọc ổ bánh mì, nướng sơ qua chảo hoặc lò nướng cho vỏ giòn rụm.', NULL, NULL),
('vn-sang-02_step_3', 'vn-sang-02', 3, 'Quết một lớp pate gan mịn màng béo ngậy vào ruột bánh.', NULL, NULL),
('vn-sang-02_step_4', 'vn-sang-02', 4, 'Kẹp trứng ốp la vào giữa, xếp dưa leo, ngò rí tươi mát lên trên.', NULL, NULL),
('vn-sang-02_step_5', 'vn-sang-02', 5, 'Rưới chút xì dầu và tương ớt cay nồng rồi thưởng thức ngay lúc nóng giòn rụm.', NULL, NULL),
('vn-sang-03_step_1', 'vn-sang-03', 1, 'Gạo rang thơm nấu cùng 1 lít nước sôi trong 15 phút đến khi hạt gạo nở bung sánh mịn.', NULL, 15),
('vn-sang-03_step_2', 'vn-sang-03', 2, 'Thịt bằm ướp hành tím, nước mắm và hạt tiêu xào săn thơm.', NULL, NULL),
('vn-sang-03_step_3', 'vn-sang-03', 3, 'Trút thịt bằm và gừng thái chỉ vào nồi cháo đang sôi khuấy đều tay trong 3 phút.', NULL, NULL),
('vn-sang-03_step_4', 'vn-sang-03', 4, 'Lót hành hoa và tía tô thái sợi dưới đáy bát sứ.', NULL, NULL),
('vn-sang-03_step_5', 'vn-sang-03', 5, 'Múc cháo nóng sôi sục lên trên, rắc nhiều tiêu đen xay làm toát mồ hôi giải cảm sảng khoái.', NULL, NULL),
('vn-sang-04_step_1', 'vn-sang-04', 1, 'Mì tôm trụng qua nước sôi 1 phút vớt ra ngay, xả nước lạnh trộn chút dầu ăn để sợi mì tơi dai.', NULL, NULL),
('vn-sang-04_step_2', 'vn-sang-04', 2, 'Phi thơm tỏi, xào thịt bò trên lửa lớn trong 1 phút rồi múc riêng ra đĩa.', NULL, NULL),
('vn-sang-04_step_3', 'vn-sang-04', 3, 'Xào rau cải chín tới, cho mì vào đảo nhanh tay cùng gói gia vị mì và 1 thìa xì dầu.', NULL, 2),
('vn-sang-04_step_4', 'vn-sang-04', 4, 'Cho thịt bò trở lại chảo đảo đều 30 giây rồi trút ra đĩa.', NULL, NULL),
('vn-sang-04_step_5', 'vn-sang-04', 5, 'Đặt quả trứng ốp la lòng đào lên trên, rạch nhẹ để lòng đỏ béo ngậy tan chảy quyện vào sợi mì.', NULL, NULL),
('vn-sang-05_step_1', 'vn-sang-05', 1, 'Đập trứng ra âu cùng 20ml sữa tươi, cà rốt băm, hành hoa và 1 thìa nước mắm, đánh tan đều.', NULL, NULL),
('vn-sang-05_step_2', 'vn-sang-05', 2, 'Quết một lớp dầu mỏng lên chảo chống dính, đun lửa nhỏ vừa rồi đổ một lớp trứng mỏng tráng đều đáy chảo.', NULL, NULL),
('vn-sang-05_step_3', 'vn-sang-05', 3, 'Khi mặt trứng se lại, dùng đũa cuộn tròn dần về một góc chảo.', NULL, NULL),
('vn-sang-05_step_4', 'vn-sang-05', 4, 'Kéo cuộn trứng lại, đổ tiếp lớp trứng mới vào nối tiếp, lặp lại quá trình cuộn tròn dày dặn.', NULL, 6),
('vn-sang-05_step_5', 'vn-sang-05', 5, 'Lấy cuộn trứng ra thớt để nguội 2 phút rồi cắt khoanh tròn 1.5cm xếp ra đĩa.', NULL, NULL),
('vn-sang-06_step_1', 'vn-sang-06', 1, 'Ức gà luộc chín xé sợi mỏng. Giữ lại nước luộc gà ngọt thơm làm nước súp.', NULL, NULL),
('vn-sang-06_step_2', 'vn-sang-06', 2, 'Đun sôi nước luộc gà, cho ngô non ngọt và nấm hương thái chỉ vào nấu trong 5 phút.', NULL, 5),
('vn-sang-06_step_3', 'vn-sang-06', 3, 'Hòa 2 thìa bột bắp với nước lọc, từ từ rót vào nồi súp khuấy đều một chiều đến khi sánh mịn óng ả.', NULL, NULL),
('vn-sang-06_step_4', 'vn-sang-06', 4, 'Đánh tan trứng gà, đổ qua rây vào nồi súp đang sôi đồng thời khuấy nhẹ tay để tạo các vân hoa trứng tuyệt đẹp.', NULL, NULL),
('vn-sang-06_step_5', 'vn-sang-06', 5, 'Múc súp ra bát, rắc ngò rí và tiêu sọ trắng thơm ấm nóng.', NULL, NULL),
('vn-lau-01_step_1', 'vn-lau-01', 1, 'Sườn sụn chần nước sôi rồi ninh nhỏ lửa 25 phút để sườn mềm giòn sần sật.', NULL, 25),
('vn-lau-01_step_2', 'vn-lau-01', 2, 'Nấu nước lọc cua đồng tạo mảng riêu cua lớn, vớt riêu ra đĩa riêng.', NULL, NULL),
('vn-lau-01_step_3', 'vn-lau-01', 3, 'Phi thơm hành khô với dầu màu điều, xào cà chua rồi trút vào nồi nước dùng cùng giấm bỗng thơm nức.', NULL, NULL),
('vn-lau-01_step_4', 'vn-lau-01', 4, 'Đổ nước sườn sụn vào hòa cùng nước riêu cua, nêm gia vị vừa vị chua thanh ngọt béo.', NULL, NULL),
('vn-lau-01_step_5', 'vn-lau-01', 5, 'Đặt nồi lẩu lên bếp từ, thả đậu rán và mảng riêu cua vào, nhúng bắp bò, sườn sụn và rau muống chẻ ăn kèm bún.', NULL, NULL),
('vn-lau-02_step_1', 'vn-lau-02', 1, 'Gà chặt miếng vừa ăn, ướp với sả băm, tỏi, ớt hiểm, nước mắm trong 20 phút.', NULL, NULL),
('vn-lau-02_step_2', 'vn-lau-02', 2, 'Phi thơm tỏi và sả cây đập dập, cho thịt gà vào xào săn chắc đều các mặt.', NULL, NULL),
('vn-lau-02_step_3', 'vn-lau-02', 3, 'Đổ 1.5 lít nước vào hầm gà lửa nhỏ trong 20 phút cho gà chín mềm ngọt nước.', NULL, 20),
('vn-lau-02_step_4', 'vn-lau-02', 4, 'Lá giang rửa sạch, dùng tay vò nhẹ cho dập lá rồi thả vào nồi nước dùng đun sôi 3 phút cho tiết vị chua dịu thanh.', NULL, NULL),
('vn-lau-02_step_5', 'vn-lau-02', 5, 'Nêm lại nước mắm vừa ăn, nhúng ngò gai ngò ôm và bún tươi thưởng thức nóng hổi.', NULL, NULL),
('vn-lau-03_step_1', 'vn-lau-03', 1, 'Hải sản sơ chế sạch sẽ, tôm bỏ chỉ lưng, mực khía bông, cá thái mỏng xếp lên đĩa cùng nấm tươi.', NULL, NULL),
('vn-lau-03_step_2', 'vn-lau-03', 2, 'Phi thơm sả cây, tỏi gừng và ớt băm với chút dầu ăn, xào thơm cà chua và dứa.', NULL, NULL),
('vn-lau-03_step_3', 'vn-lau-03', 3, 'Đổ 1.8 lít nước hầm xương vào đun sôi bùng, vắt nước cốt chanh me và lá chanh vò dập tạo hương thơm lừng.', NULL, 10),
('vn-lau-03_step_4', 'vn-lau-03', 4, 'Nêm nếm nước dùng chua chua cay cay hài hòa đậm đà.', NULL, NULL),
('vn-lau-03_step_5', 'vn-lau-03', 5, 'Đặt lên bàn tiệc, nhúng tôm, mực, cá và nấm kim châm ăn liền khi vừa chín tới để cảm nhận độ giòn ngọt mọng nước.', NULL, NULL),
('vn-lau-04_step_1', 'vn-lau-04', 1, 'Gà ta rửa sạch chần sơ nước sôi, cho vào nồi ninh cùng bắp ngọt và cà rốt 25 phút để lấy nước dùng ngọt thanh.', NULL, 25),
('vn-lau-04_step_2', 'vn-lau-04', 2, 'Các loại nấm tươi cắt bỏ gốc bẩn, rửa nhẹ tay với nước muối loãng rồi xếp ra khay lớn.', NULL, NULL),
('vn-lau-04_step_3', 'vn-lau-04', 3, 'Nêm nếm nước lẩu thanh đạm với muối khoáng và hạt nêm nấm, không dùng quá nhiều gia vị cay nồng.', NULL, NULL),
('vn-lau-04_step_4', 'vn-lau-04', 4, 'Bày nồi lẩu ra giữa bàn, thả đậu hũ non và một phần nấm hương vào đun sôi.', NULL, NULL),
('vn-lau-04_step_5', 'vn-lau-04', 5, 'Nhúng các loại nấm tươi vào nước lẩu sôi trong 2 phút rồi vớt ra ăn ngay giữ trọn vị giòn ngọt thanh tao.', NULL, NULL),
('vn-lau-05_step_1', 'vn-lau-05', 1, 'Cá thác lác nêm nước mắm, hành hoa, tiêu sọ trắng, quết liên tục 15 phút đến khi chả cá dẻo dính chặt vào tô.', NULL, NULL),
('vn-lau-05_step_2', 'vn-lau-05', 2, 'Khổ qua bào lát mỏng tang, ngâm vào thau nước đá lạnh 15 phút để khổ qua giòn rụm và bớt đắng.', NULL, NULL),
('vn-lau-05_step_3', 'vn-lau-05', 3, 'Nấu nước dùng từ xương heo ngọt trong, nêm nếm gia vị thanh dịu.', NULL, NULL),
('vn-lau-05_step_4', 'vn-lau-05', 4, 'Dùng muỗng múc từng viên chả cá thác lác thả vào nồi lẩu sôi, khi viên chả nổi lên là chín tới phồng to.', NULL, NULL),
('vn-lau-05_step_5', 'vn-lau-05', 5, 'Gắp khổ qua nhúng nhanh vào nồi lẩu 10 giây rồi vớt ra ăn liền cùng chả cá dai ngọt và bún tươi.', NULL, NULL)
ON CONFLICT(id) DO UPDATE SET
  recipe_id = excluded.recipe_id,
  step_number = excluded.step_number,
  instruction = excluded.instruction,
  tip = excluded.tip,
  timer_minutes = excluded.timer_minutes;
